## created before run helm pipeline as the helm zeva-backend deployment needs it
apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: DJANGO_SECRET
  description: "Cookie used for authentication of cluster nodes"
  from: "[a-zA-Z0-9]{50}"
  generate: expression
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: zeva-django
  stringData:
    DJANGO_SECRET_KEY: ${DJANGO_SECRET}