apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: jenkins
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      shared: "true"
    name: ${NAME}-slave-${SLAVE_NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}-slave-${SLAVE_NAME}${SUFFIX}
  spec:
    failedBuildsHistoryLimit: 2
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-slave-${SLAVE_NAME}:${VERSION}
    postCommit: {}
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    runPolicy: SerialLatestOnly
    source:
      git:
        ref: ${SOURCE_GIT_REF}
        uri: ${SOURCE_GIT_URL}
      type: Git
      contextDir: .jenkins/openshift
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ${SOURCE_IMAGE_STREAM_TAG}
          namespace: ${SOURCE_IMAGE_STREAM_NAMESPACE}
        dockerfilePath: Dockerfile-slave
      type: Docker
    successfulBuildsHistoryLimit: 2
    triggers:
    - type: ConfigChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: ${SOURCE_IMAGE_STREAM_TAG}
          namespace: ${SOURCE_IMAGE_STREAM_NAMESPACE}
      type: ImageChange
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: jenkins
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: "-0"
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: latest
- name: SLAVE_NAME
  value: build
- name: SOURCE_IMAGE_STREAM_NAMESPACE
  value: tbiwaq-tools
- name: SOURCE_IMAGE_STREAM_TAG
  required: true
  value: "jenkins-slave-main:jenkins-slave-python3nodejs-20200218"
- name: SOURCE_GIT_URL
  required: true
  value: https://github.com/bcgov/zeva.git
- name: SOURCE_GIT_REF
  required: true
  value: pipeline-jenkins
- name: SOURCE_CONTEXT_DIR
  required: true
  value: .jenkins/docker-slave
