# Generated by Django 3.2.20 on 2023-09-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_auto_20230928_1225"),
    ]

    operations = [
        migrations.AddField(
            model_name="salessubmissioncontent",
            name="warnings_list",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
