# Generated by Django 3.0.2 on 2020-01-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_organizationaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_government',
            field=models.BooleanField(default=False),
        ),
    ]
