# Generated by Django 3.2.20 on 2023-10-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230918_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelyearreportassessment',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelyearreportassessmentcomment',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelyearreportldvsales',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelyearreportmake',
            name='display',
            field=models.BooleanField(default=True),
        )
    ]
