# Generated by Django 3.0.2 on 2020-01-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_organization_is_government'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
