# Generated by Django 3.2.18 on 2024-04-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231024_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelyearreportcomplianceobligation',
            name='reduction_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        )
    ]
