# Generated by Django 3.2.25 on 2024-07-18 19:33

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240508_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackdatedCreditTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('compliance_year', models.IntegerField()),
                ('accounted_for_in_supplemental', models.BooleanField()),
                ('accounted_for_in_model_year_report', models.BooleanField()),
                ('credit_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backdated_credit_transaction', to='api.credittransaction')),
            ],
            options={
                'db_table': 'backdated_credit_transaction',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
