# Generated by Django 3.2.25 on 2024-08-20 00:01

import api.constants.zev_type
import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240508_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('ice_vehicles_one', models.IntegerField(blank=True, null=True)),
                ('ice_vehicles_two', models.IntegerField(blank=True, null=True)),
                ('ice_vehicles_three', models.IntegerField(blank=True, null=True)),
                ('zev_vehicles_one', models.IntegerField(blank=True, null=True)),
                ('zev_vehicles_two', models.IntegerField(blank=True, null=True)),
                ('zev_vehicles_three', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales_forecast',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='SalesForecastRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('model_year', models.CharField(max_length=4)),
                ('make', models.CharField(max_length=250)),
                ('model_name', models.CharField(max_length=250)),
                ('type', enumfields.fields.EnumField(enum=api.constants.zev_type.ZEV_TYPE, max_length=10)),
                ('range', models.DecimalField(decimal_places=2, max_digits=20)),
                ('zev_class', models.CharField(max_length=1)),
                ('vehicle_class', models.CharField(max_length=250)),
                ('total_supplied', models.IntegerField()),
                ('sales_forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salesforecast')),
            ],
            options={
                'db_table': 'sales_forecast_record',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='model_year_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelyearreport', unique=True),
        ),
    ]
