# Generated by Django 3.0.2 on 2020-01-13 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='credit_value',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CreditValue'),
        ),
    ]
