# Generated by Django 3.0.2 on 2020-01-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200113_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditvalue',
            old_name='a',
            new_name='class_a_credit_value',
        ),
        migrations.RenameField(
            model_name='creditvalue',
            old_name='b',
            new_name='class_b_credit_value',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='validated',
            new_name='is_validated',
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(db_column='description', max_length=250),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(db_column='description', max_length=250),
        ),
        migrations.AlterField(
            model_name='modelyear',
            name='name',
            field=models.CharField(db_column='description', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_column='organization_name', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='trim',
            name='name',
            field=models.CharField(db_column='description', max_length=250),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(db_column='description', max_length=250),
        ),
        migrations.AlterModelTable(
            name='creditvalue',
            table='credit_value',
        ),
        migrations.AlterModelTable(
            name='make',
            table='vehicle_make',
        ),
        migrations.AlterModelTable(
            name='model',
            table='vehicle_model',
        ),
        migrations.AlterModelTable(
            name='trim',
            table='vehicle_trim',
        ),
        migrations.AlterModelTable(
            name='type',
            table='vehicle_type',
        ),
    ]
