# Generated by Django 3.2.25 on 2024-10-03 21:25

from django.db import migrations, models

def update_compliance_ratios(apps, schema_editor):
    ComplianceRatio = apps.get_model('api', 'ComplianceRatio')
    
    ratios = [
        (2026, 26.30, 15.20),
        (2027, 42.60, 28.70),
        (2028, 58.90, 43.20),
        (2029, 74.80, 58.00),
        (2030, 91.00, 73.30),
        (2031, 93.20, 77.20),
        (2032, 95.20, 80.60),
        (2033, 97.20, 83.70),
        (2034, 99.30, 86.70),
        (2035, 100.00, 89.50),
    ]

    for year, ratio, zev_class_a in ratios:
        compliance_ratio = ComplianceRatio.objects.get(model_year=year)
        compliance_ratio.compliance_ratio = ratio
        compliance_ratio.zev_class_a = zev_class_a
        compliance_ratio.save()

def delete_compliance_ratios(apps, schema_editor):
    ComplianceRatio = apps.get_model('api', 'ComplianceRatio')
    ComplianceRatio.objects.filter(model_year__gte=2036).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240828_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complianceratio',
            options={'ordering': ['model_year']},
        ),
        migrations.RunPython(update_compliance_ratios),
        migrations.RunPython(delete_compliance_ratios),
    ]
