# Generated by Django 3.0.2 on 2020-01-20 06:36

import api.models.vehicle
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200113_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='validated',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='state',
            field=enumfields.fields.EnumField(default=api.models.vehicle.VehicleDefinitionStates.NEW, enum=api.models.vehicle.VehicleDefinitionStates, max_length=20),
        ),
    ]
