# Generated by Django 3.2.25 on 2024-12-09 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20241003_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelyearreportassessmentcomment',
            name='comment',
            field=models.TextField(blank=True, db_column='assessment_comment', null=True),
        ),
    ]
