# Generated by Django 3.0.2 on 2020-01-20 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200120_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
            preserve_default=False,
        ),
    ]
