# Generated by Django 3.0.2 on 2020-01-20 06:36

import api.models.vehicle
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200120_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_validated',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='state',
            field=enumfields.fields.EnumField(default=api.models.vehicle_statuses.VehicleDefinitionStatuses.NEW, enum=api.models.vehicle_statuses.VehicleDefinitionStatuses, max_length=20),
        ),
    ]
