# Generated by Django 3.2.25 on 2025-01-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20241209_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationldvsales',
            name='is_supplied',
            field=models.BooleanField(default=False),
        ),
    ]
