# Generated by Django 3.0.2 on 2020-01-20 06:57

import api.models.vehicle
import db_comments.model_mixins
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200120_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('in_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('previous_state', enumfields.fields.EnumField(default='NEW', enum=api.models.vehicle_statuses.VehicleDefinitionStatuses, max_length=20)),
                ('current_state', enumfields.fields.EnumField(default='NEW', enum=api.models.vehicle_statuses.VehicleDefinitionStatuses, max_length=20)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.UserProfile')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_vehiclechangehistory_CREATE_USER', to='api.UserProfile')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_vehiclechangehistory_UPDATE_USER', to='api.UserProfile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='api.Vehicle')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
