# Generated by Django 3.2.25 on 2025-01-31 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20250115_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountbalance',
            options={'managed': True},
        ),
        migrations.DeleteModel(
            name='AccountBalance',
        ),
    ]
