# Generated by Django 3.0.2 on 2020-01-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_vehiclechangehistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehiclechangehistory',
            table='vehicle_change_history',
        ),
    ]
