# Generated by Django 3.2.25 on 2026-01-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20250131_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcbcUploadProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('progress', models.IntegerField(default=0)),
                ('status_text', models.CharField(default='Starting...', max_length=255)),
                ('current_page', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'icbc_upload_progress',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='credittransfer',
            name='credit_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.organization'),
        ),
        migrations.AlterField(
            model_name='credittransfer',
            name='debit_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.organization'),
        ),
        migrations.AlterField(
            model_name='credittransfercomment',
            name='credit_transfer_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transfer_comments', to='api.credittransferhistory'),
        ),
        migrations.AlterField(
            model_name='credittransfercontent',
            name='credit_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.creditclass'),
        ),
        migrations.AlterField(
            model_name='credittransfercontent',
            name='credit_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='credittransfercontent',
            name='dollar_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='credittransfercontent',
            name='model_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.modelyear'),
        ),
        migrations.AlterField(
            model_name='credittransfercontent',
            name='weight_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.weightclass'),
        ),
        migrations.AlterField(
            model_name='icbcregistrationdata',
            name='icbc_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.icbcvehicle'),
        ),
        migrations.AlterField(
            model_name='modelyearreport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.organization'),
        ),
        migrations.AlterField(
            model_name='modelyearreportassessmentdescriptions',
            name='display_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modelyearreportvehicle',
            name='model_year_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.modelyearreport'),
        ),
    ]
