# Generated by Django 3.2.25 on 2026-01-15 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20250131_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcbcUploadProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, blank=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('upload_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('progress', models.IntegerField(default=0)),
                ('status_text', models.CharField(default='Starting...', max_length=255)),
                ('current_page', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'icbc_upload_progress',
            },
        ),
    ]
