# Generated by Django 3.0.2 on 2020-01-20 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200120_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclechangehistory',
            name='at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
