# Generated by Django 3.2.25 on 2026-01-19 19:48

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20250131_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcbcUploadProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('status_text', models.CharField(default='Starting...', max_length=255)),
                ('current_page', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
                ('upload', models.OneToOneField(db_column='upload_id', on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.icbcuploaddate')),
            ],
            options={
                'db_table': 'icbc_upload_progress',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
