# Generated by Django 3.0.2 on 2020-01-24 18:16

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_vehiclechangehistory_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMakeOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_vehiclemakeorganization_CREATE_USER', to='api.UserProfile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_make_organizations', to='api.Organization')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_vehiclemakeorganization_UPDATE_USER', to='api.UserProfile')),
                ('vehicle_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_make_organizations', to='api.Make')),
            ],
            options={
                'db_table': 'vehicle_make_organization',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
