# Generated by Django 3.0.2 on 2020-01-24 19:35

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_vehiclechangehistory_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(db_column='description', max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(db_column='description', max_length=250)),
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_vehicleclass_CREATE_USER', to='api.UserProfile')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_vehicleclass_UPDATE_USER', to='api.UserProfile')),
            ],
            options={
                'db_table': 'vehicle_class',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(db_column='description', max_length=250)),
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_fueltype_CREATE_USER', to='api.UserProfile')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_fueltype_UPDATE_USER', to='api.UserProfile')),
            ],
            options={
                'db_table': 'vehicle_fuel_type',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.ForeignKey(db_column='fuel_type_code', default='B', on_delete=django.db.models.deletion.PROTECT, to='api.FuelType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_class',
            field=models.ForeignKey(db_column='vehicle_class_code', default='M', on_delete=django.db.models.deletion.PROTECT, to='api.VehicleClass'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('make', 'model', 'vehicle_class', 'fuel_type', 'model_year')},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='credit_value',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='trim',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
