# Generated by Django 3.0.2 on 2020-01-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200127_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='model_name',
            field=models.CharField(default='modelname', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('make', 'model_name', 'vehicle_class_code', 'vehicle_fuel_type', 'model_year')},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
    ]
