# Generated by Django 3.0.2 on 2020-02-04 18:28

import api.models.vehicle_statuses
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200130_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='model',
            name='make',
        ),
        migrations.RemoveField(
            model_name='model',
            name='update_user',
        ),
        migrations.RemoveField(
            model_name='trim',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='trim',
            name='model',
        ),
        migrations.RemoveField(
            model_name='trim',
            name='update_user',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='state',
            new_name='validation_status',
        ),
        migrations.RemoveField(
            model_name='vehiclechangehistory',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='vehiclechangehistory',
            name='at',
        ),
        migrations.RemoveField(
            model_name='vehiclechangehistory',
            name='create_timestamp',
        ),
        migrations.RemoveField(
            model_name='vehiclechangehistory',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='vehiclechangehistory',
            name='current_state',
        ),
        migrations.RemoveField(
            model_name='vehiclechangehistory',
            name='in_roles',
        ),
        migrations.RemoveField(
            model_name='vehiclechangehistory',
            name='previous_state',
        ),
        migrations.RemoveField(
            model_name='vehiclechangehistory',
            name='update_timestamp',
        ),
        migrations.RemoveField(
            model_name='vehiclechangehistory',
            name='update_user',
        ),
        migrations.AddField(
            model_name='vehiclechangehistory',
            name='make_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehiclechangehistory',
            name='model_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vehiclechangehistory',
            name='model_year_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehiclechangehistory',
            name='range',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehiclechangehistory',
            name='user_role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='vehiclechangehistory',
            name='validation_status',
            field=enumfields.fields.EnumField(default='NEW', enum=api.models.vehicle_statuses.VehicleDefinitionStatuses, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiclechangehistory',
            name='vehicle_class_code_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehiclechangehistory',
            name='vehicle_fuel_type_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiclechangehistory',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.Vehicle'),
        ),
        migrations.DeleteModel(
            name='CreditValue',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Trim',
        ),
    ]
