# Generated by Django 3.0.3 on 2020-02-25 07:42

import api.models.vehicle_statuses
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200204_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='validation_status',
            field=enumfields.fields.EnumField(default='DRAFT', enum=api.models.vehicle_statuses.VehicleDefinitionStatuses, max_length=20),
        ),
    ]
