# Generated by Django 3.0.3 on 2020-02-25 07:46

import api.models.record_of_sale_statuses
import api.models.vin_statuses
import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200224_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordOfSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('sale_id', models.CharField(blank=True, max_length=255, null=True)),
                ('vin', models.CharField(blank=True, max_length=20, null=True)),
                ('vin_validation_status', enumfields.fields.EnumField(default=('UNCHECKED'), enum=api.models.vin_statuses.VINStatuses, max_length=30)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('submission_date', models.DateField(auto_now=True, null=True)),
                ('validation_status', enumfields.fields.EnumField(default=('NEW'), enum=api.models.record_of_sale_statuses.RecordOfSaleStatuses, max_length=20)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_recordofsale_CREATE_USER', to='api.UserProfile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.Organization')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_recordofsale_UPDATE_USER', to='api.UserProfile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.Vehicle')),
            ],
            options={
                'db_table': 'record_of_sale',
                'unique_together': {('organization', 'sale_id')},
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
