# Generated by Django 3.0.3 on 2020-03-06 04:50

import api.models.record_of_sale_statuses
import api.models.sales_submission_statuses
import api.models.vin_statuses
import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200225_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordofsale',
            name='validation_status',
            field=enumfields.fields.EnumField(default='NEW', enum=api.models.record_of_sale_statuses.RecordOfSaleStatuses, max_length=20),
        ),
        migrations.AlterField(
            model_name='recordofsale',
            name='vin_validation_status',
            field=enumfields.fields.EnumField(default='UNCHECKED', enum=api.models.vin_statuses.VINStatuses, max_length=30),
        ),
        migrations.CreateModel(
            name='SalesSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_column='description', max_length=250, unique=True)),
                ('submission_date', models.DateField(auto_now=True, null=True)),
                ('validation_status', enumfields.fields.EnumField(default='NEW', enum=api.models.sales_submission_statuses.SalesSubmissionStatuses, max_length=20)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_salessubmission_CREATE_USER', to='api.UserProfile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.Organization')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_salessubmission_UPDATE_USER', to='api.UserProfile')),
            ],
            options={
                'db_table': 'sales_submission',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.AddField(
            model_name='recordofsale',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.SalesSubmission'),
        ),
    ]
