# Generated by Django 3.0.3 on 2020-03-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_map_records_to_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordofsale',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='recordofsale',
            name='submission_date',
        ),
        migrations.AlterField(
            model_name='recordofsale',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.SalesSubmission'),
        ),
    ]
