# Generated by Django 3.0.3 on 2020-03-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200309_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(db_column='short_name', max_length=64, null=True, unique=True),
        ),
    ]
