# Generated by Django 3.0.3 on 2020-03-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_organization_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salessubmission',
            name='submission_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
