# Generated by Django 3.0.3 on 2020-03-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200310_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salessubmission',
            name='submission_sequence',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
