# Generated by Django 3.0.3 on 2020-03-12 09:28
from datetime import datetime

from django.db import migrations
from django.db.migrations import RunPython


def create_initial_credit_transaction_data(apps, schema_editor):

    db_alias = schema_editor.connection.alias

    CreditClass = apps.get_model('api', 'CreditClass')
    CreditTransactionType = apps.get_model('api', 'CreditTransactionType')


    CreditClass.objects.using(db_alias).create(
        credit_class='A',
        effective_date=datetime.now(),
    )
    CreditClass.objects.using(db_alias).create(
        credit_class='B',
        effective_date=datetime.now(),
    )
    CreditTransactionType.objects.using(db_alias).create(
        transaction_type='Validation',
    )
    CreditTransactionType.objects.using(db_alias).create(
        transaction_type='Reduction',
    )


def drop_initial_credit_transaction_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    CreditClass = apps.get_model('api', 'CreditClass')
    CreditTransactionType = apps.get_model('api', 'CreditTransactionType')

    CreditClass.objects.using(db_alias).get(credit_class='A').delete()
    CreditClass.objects.using(db_alias).get(credit_class='B').delete()
    CreditTransactionType.objects.using(db_alias).get(transaction_type='Validation').delete()
    CreditTransactionType.objects.using(db_alias).get(transaction_type='Reduction').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_creditclass_credittransaction_credittransactiontype'),
    ]

    operations = [
        RunPython(create_initial_credit_transaction_data, drop_initial_credit_transaction_data)
    ]
