# Generated by Django 3.0.3 on 2020-03-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_credit_transactions_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credittransaction',
            old_name='timestamp',
            new_name='transaction_timestamp',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='credit_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.CreditClass'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='credit_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
