# Generated by Django 3.0.3 on 2020-03-25 23:23

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200311_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcbcData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=20, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_icbcdata_CREATE_USER', to='api.UserProfile')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_icbcdata_UPDATE_USER', to='api.UserProfile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Vehicle')),
            ],
            options={
                'db_table': 'icbc_data',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
