# Generated by Django 3.0.3 on 2020-04-16 15:11

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_icbcregistrationdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordofsale',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='icbcregistrationdata',
            name='vehicle',
        ),
        migrations.CreateModel(
            name='IcbcVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('model_name', models.CharField(max_length=250)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_icbcvehicle_CREATE_USER', to='api.UserProfile')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Make')),
                ('model_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ModelYear')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_icbcvehicle_UPDATE_USER', to='api.UserProfile')),
            ],
            options={
                'db_table': 'icbc_vehicle',
                'unique_together': {('make', 'model_name', 'model_year')},
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.AddField(
            model_name='icbcregistrationdata',
            name='icbc_vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.IcbcVehicle'),
            preserve_default=False,
        ),
    ]
