# Generated by Django 3.0.3 on 2020-05-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20200429_1327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('make', 'model_name', 'vehicle_zev_type', 'model_year')},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_class_code',
        ),
    ]
