# Generated by Django 3.0.3 on 2020-05-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20200508_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleclass',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='vehicleclass',
            name='update_user',
        ),
        migrations.RemoveField(
            model_name='vehiclemakeorganization',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='vehiclemakeorganization',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='vehiclemakeorganization',
            name='update_user',
        ),
        migrations.RemoveField(
            model_name='vehiclemakeorganization',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='vehiclechangehistory',
            name='make_id',
        ),
        migrations.AlterField(
            model_name='icbcvehicle',
            name='make',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.DeleteModel(
            name='Make',
        ),
        migrations.DeleteModel(
            name='VehicleClass',
        ),
        migrations.DeleteModel(
            name='VehicleMakeOrganization',
        ),
    ]
