# Generated by Django 3.0.3 on 2020-05-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20200513_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclechangehistory',
            name='vehicle_class_code_id',
        ),
        migrations.AddField(
            model_name='vehiclechangehistory',
            name='make',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
