# Generated by Django 3.0.3 on 2020-05-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20200514_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icbcvehicle',
            name='make',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=250),
        ),
    ]
