# Generated by Django 3.0.3 on 2020-05-20 20:25

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_permission_role_rolepermission_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclechangehistory',
            name='vehicle_class_code_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(db_column='description', max_length=250)),
                ('vehicle_class_code', models.CharField(max_length=3, unique=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_vehicleclass_CREATE_USER', to='api.UserProfile')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_vehicleclass_UPDATE_USER', to='api.UserProfile')),
            ],
            options={
                'db_table': 'vehicle_class_code',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
