# Generated by Django 3.0.3 on 2020-05-20 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20200520_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_class_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.VehicleClass'),
            preserve_default=False,
        ),
    ]
