# Generated by Django 3.0.3 on 2020-05-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20200521_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='api.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclechangehistory',
            name='organization_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
