# Generated by Django 3.0.3 on 2020-05-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20200521_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleclass',
            name='create_user',
            field=models.CharField(default='SYSTEM', max_length=130),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='update_user',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
