# Generated by Django 3.0.3 on 2020-05-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20200525_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_filename', models.CharField(max_length=255)),
                ('applied', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fixture_migrations',
            },
        ),
    ]
