# Generated by Django 3.0.3 on 2020-05-29 18:58

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_fixturemigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcbcUploadDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('upload_date', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'icbc_upload_date',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.AddField(
            model_name='icbcregistrationdata',
            name='icbc_upload_date',
            field=models.ForeignKey(default='20200529', on_delete=django.db.models.deletion.CASCADE, to='api.IcbcUploadDate'),
            preserve_default=False,
        ),
    ]
