# Generated by Django 3.0.3 on 2020-05-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20200529_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icbcuploaddate',
            name='upload_date',
            field=models.DateField(auto_now=True, default='2020-05-29'),
            preserve_default=False,
        ),
    ]
