# Generated by Django 3.0.3 on 2020-06-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20200529_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vehiclechangehistory',
            name='vehicle_comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
