# Generated by Django 3.0.3 on 2020-06-24 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20200610_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='vehicle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Vehicle'),
            preserve_default=False,
        ),
    ]
