# Generated by Django 3.0.3 on 2020-07-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_accountbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbalance',
            name='credit_class',
        ),
        migrations.RemoveField(
            model_name='credittransaction',
            name='credit_class',
        ),
        migrations.RemoveField(
            model_name='credittransaction',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='credit_class',
        ),
        migrations.AlterField(
            model_name='creditclass',
            name='credit_class',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='credittransactiontype',
            name='transaction_type',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='creditclass',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittransactiontype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
