# Generated by Django 3.0.3 on 2020-07-20 13:53

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20200715_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('weight_class_code', models.CharField(max_length=3, unique=True)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'weight_class_code',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.RemoveField(
            model_name='credittransaction',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='model_year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='api.ModelYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='weight_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.WeightClass'),
            preserve_default=False,
        ),
    ]
