# Generated by Django 3.0.3 on 2020-07-20 17:46

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20200720_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_comment',
        ),
        migrations.RemoveField(
            model_name='vehiclechangehistory',
            name='vehicle_comment',
        ),
        migrations.AlterField(
            model_name='icbcuploaddate',
            name='upload_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='VehicleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('comment', models.CharField(blank=True, db_column='vehicle_comment', max_length=4000, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_comments', to='api.Vehicle')),
            ],
            options={
                'db_table': 'vehicle_comment',
                'ordering': ['create_timestamp'],
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
