# Generated by Django 3.0.3 on 2020-07-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20200720_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icbcuploaddate',
            name='upload_date',
            field=models.DateField(),
        ),
    ]
