# Generated by Django 3.0.3 on 2020-07-24 21:04

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20200717_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSubmissionContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('xls_make', models.CharField(blank=True, max_length=255, null=True)),
                ('xls_model', models.CharField(blank=True, max_length=255, null=True)),
                ('xls_model_year', models.CharField(blank=True, max_length=255, null=True)),
                ('xls_sale_date', models.CharField(blank=True, max_length=255, null=True)),
                ('xls_vin', models.CharField(blank=True, max_length=255, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.SalesSubmission')),
            ],
            options={
                'db_table': 'sale_submission_content',
                'ordering': ['id'],
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
