# Generated by Django 3.0.3 on 2020-08-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_salessubmissioncontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessubmissioncontent',
            name='xls_date_mode',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salessubmissioncontent',
            name='xls_date_type',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
