# Generated by Django 3.0.3 on 2020-08-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20200804_1403'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salessubmissioncontent',
            table='sales_submission_content',
        ),
    ]
