# Generated by Django 3.0.3 on 2020-08-20 21:52

import api.models.credit_transfer_statuses
import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20200806_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('number_of_credits', models.IntegerField()),
                ('value_per_credit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', enumfields.fields.EnumField(default='DRAFT', enum=api.models.credit_transfer_statuses.CreditTransferStatuses, max_length=20)),
                ('credit_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.CreditClass')),
                ('from_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Organization')),
                ('model_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ModelYear')),
                ('to_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Organization')),
            ],
            options={
                'db_table': 'credit_transfer',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
