# Generated by Django 3.0.3 on 2020-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20200806_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='has_passed_us06_test',
            field=models.BooleanField(default=False),
        ),
    ]
