# Generated by Django 3.0.3 on 2020-08-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20200806_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='additional_credit',
            field=models.BooleanField(default=False),
        ),
    ]
