# Generated by Django 3.0.3 on 2020-08-26 17:02

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_credittransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('address_type', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'address_type',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='address_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.AddressType'),
            preserve_default=False,
        ),
    ]
