# Generated by Django 3.0.3 on 2020-08-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_credittransfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='has_passed_us06_test',
            new_name='has_passed_us_06_test',
        ),
    ]
