# Generated by Django 3.0.3 on 2020-09-02 14:45

import api.models.sales_submission_statuses
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20200824_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salessubmission',
            name='validation_status',
            field=enumfields.fields.EnumField(default='DRAFT', enum=api.models.sales_submission_statuses.SalesSubmissionStatuses, max_length=20),
        ),
    ]
