# Generated by Django 3.0.3 on 2020-09-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20200903_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransfer',
            name='credit_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittransfer',
            name='debit_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.Organization'),
            preserve_default=False,
        ),
    ]
