# Generated by Django 3.0.3 on 2020-09-08 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20200904_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransfercontent',
            name='credit_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transfer_content', to='api.CreditTransaction'),
        ),
    ]
