# Generated by Django 3.0.3 on 2020-09-09 18:18

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20200908_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransfercontent',
            name='credit_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transfer_content', to='api.CreditTransaction'),
        ),
        migrations.CreateModel(
            name='SalesSubmissionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('comment', models.CharField(blank=True, db_column='sales_submission_comment', max_length=4000, null=True)),
                ('sales_submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_submission_comments', to='api.SalesSubmission')),
            ],
            options={
                'db_table': 'sales_submission_comment',
                'ordering': ['create_timestamp'],
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
