# Generated by Django 3.0.3 on 2020-09-28 22:33

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20200909_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credittransfercontent',
            name='credit_transaction',
        ),
        migrations.AddField(
            model_name='credittransfercontent',
            name='credit_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.CreditClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittransfercontent',
            name='credit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittransfercontent',
            name='dollar_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittransfercontent',
            name='model_year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='api.ModelYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credittransfercontent',
            name='weight_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.WeightClass'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SalesSubmissionCreditTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('credit_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_submission_credit_transaction', to='api.CreditTransaction')),
                ('sales_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_submission_credit_transaction', to='api.SalesSubmission')),
            ],
            options={
                'db_table': 'sales_submission_credit_transaction',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='CreditTransferCreditTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('credit_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transfer_credit_transaction', to='api.CreditTransaction')),
                ('credit_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transfer_credit_transaction', to='api.CreditTransfer')),
            ],
            options={
                'db_table': 'credit_transfer_credit_transaction',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
