# Generated by Django 3.0.3 on 2020-10-06 22:56

import api.models.sales_submission_statuses
import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20200928_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSubmissionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('validation_status', enumfields.fields.EnumField(default='DRAFT', enum=api.models.sales_submission_statuses.SalesSubmissionStatuses, max_length=20)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.SalesSubmission')),
            ],
            options={
                'db_table': 'sales_submission_history',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
