# Generated by Django 3.0.3 on 2020-10-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_salessubmissionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessubmission',
            name='filename',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
