# Generated by Django 3.0.3 on 2020-10-22 20:58

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_salessubmission_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salessubmissionhistory',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='api.SalesSubmission'),
        ),
        migrations.CreateModel(
            name='CreditTransferComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('comment', models.CharField(blank=True, db_column='credit_transfer_comment', max_length=4000, null=True)),
                ('credit_transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transfer_comments', to='api.CreditTransfer')),
            ],
            options={
                'db_table': 'credit_transfer_comment',
                'ordering': ['create_timestamp'],
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
