# Generated by Django 3.0.3 on 2020-10-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_salessubmission_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salessubmissionhistory',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='api.SalesSubmission'),
        ),
    ]
