# Generated by Django 3.0.3 on 2020-10-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20201022_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationaddress',
            name='representative_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
