# Generated by Django 3.0.3 on 2020-11-06 21:50

import api.models.credit_transfer_statuses
import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_organizationaddress_representative_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransferHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('status', enumfields.fields.EnumField(default='DRAFT', enum=api.models.credit_transfer_statuses.CreditTransferStatuses, max_length=20)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='api.CreditTransfer')),
            ],
            options={
                'db_table': 'credit_transfer_history',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
