# Generated by Django 3.0.3 on 2020-11-18 18:13

import api.models.signing_authority_assertion
import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_credittransferhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningAuthorityAssertion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('display_order', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('module', models.CharField(choices=[(api.models.signing_authority_assertion.SigningAuthorityAssertion.AssertionModules['CREDIT_TRANSFER'], 'CREDIT_TRANSFER')], default='credit_transfer', max_length=50)),
            ],
            options={
                'db_table': 'signing_authority_assertion',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='SigningAuthorityConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('has_accepted', models.BooleanField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_transfer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='confirmations', to='api.CreditTransfer')),
                ('signing_authority_assertion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='api.SigningAuthorityAssertion')),
            ],
            options={
                'db_table': 'signing_authority_confirmation',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
