# Generated by Django 3.0.3 on 2020-11-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_signingauthorityassertion_signingauthorityconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icbcregistrationdata',
            name='vin',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='icbcvehicle',
            name='make',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='icbcvehicle',
            name='model_name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='salessubmissioncontent',
            name='xls_make',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salessubmissioncontent',
            name='xls_model',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salessubmissioncontent',
            name='xls_model_year',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salessubmissioncontent',
            name='xls_vin',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterIndexTogether(
            name='icbcvehicle',
            index_together={('make', 'model_name', 'model_year')},
        ),
    ]
