# Generated by Django 3.0.3 on 2020-12-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20201125_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credittransfercomment',
            name='credit_transfer',
        ),
        migrations.AddField(
            model_name='credittransfercomment',
            name='credit_transfer_history',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transfer_comments', to='api.CreditTransferHistory'),
            preserve_default=False,
        ),
    ]
