# Generated by Django 3.0.3 on 2021-01-20 16:53

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_notification_notificationsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('filename', models.CharField(max_length=260)),
                ('minio_object_name', models.CharField(max_length=32)),
                ('size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_evidence', to='api.SalesSubmission')),
            ],
            options={
                'db_table': 'sale_submission_file_attachment',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
