# Generated by Django 3.0.7 on 2021-01-28 20:12

import db_comments.model_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20210120_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('model_year', models.CharField(max_length=250)),
                ('compliance_ratio', models.CharField(max_length=250)),
                ('zev_class_a', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'compliance_ratio',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
