# Generated by Django 3.0.7 on 2021-02-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_complianceratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceratio',
            name='compliance_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='complianceratio',
            name='zev_class_a',
            field=models.FloatField(),
        ),
    ]
