# Generated by Django 3.0.7 on 2021-02-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20210201_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceratio',
            name='compliance_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='complianceratio',
            name='zev_class_a',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
