# Generated by Django 3.0.7 on 2021-02-10 20:45

import api.models.model_year_report_statuses
import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20210203_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelYearReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('organization_name', models.CharField(max_length=500)),
                ('supplier_class', models.CharField(max_length=1)),
                ('validation_status', enumfields.fields.EnumField(default='DRAFT', enum=api.models.model_year_report_statuses.ModelYearReportStatuses, max_length=20)),
                ('model_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ModelYear')),
            ],
            options={
                'db_table': 'model_year_report',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='ModelYearReportMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('make', models.CharField(max_length=250)),
                ('model_year_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_year_report_makes', to='api.ModelYearReport')),
            ],
            options={
                'db_table': 'model_year_report_make',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='ModelYearReportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('validation_status', enumfields.fields.EnumField(default='DRAFT', enum=api.models.model_year_report_statuses.ModelYearReportStatuses, max_length=20)),
                ('model_year_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_year_report_history', to='api.ModelYearReport')),
            ],
            options={
                'db_table': 'model_year_report_history',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='ModelYearReportConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('has_accepted', models.BooleanField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('model_year_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_year_report_confirmations', to='api.ModelYearReport')),
                ('signing_authority_assertion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_year_report_confirmations', to='api.SigningAuthorityAssertion')),
            ],
            options={
                'db_table': 'model_year_report_confirmation',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
