# Generated by Django 3.0.7 on 2021-02-10 23:12

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_modelyearreport_modelyearreportconfirmation_modelyearreporthistory_modelyearreportmake'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelYearReportAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('representative_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=500, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('other', models.CharField(blank=True, max_length=100, null=True)),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.AddressType')),
                ('model_year_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_year_report_addresses', to='api.ModelYearReport')),
            ],
            options={
                'db_table': 'model_year_report_address',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
