# Generated by Django 3.0.7 on 2021-02-10 21:57

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_modelyearreport_modelyearreportconfirmation_modelyearreporthistory_modelyearreportmake'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelyearreport',
            name='ldv_sales',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='ModelYearReportVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('pending_sales', models.IntegerField()),
                ('sales_issued', models.IntegerField()),
                ('make', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('range', models.DecimalField(decimal_places=2, max_digits=20)),
                ('model_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ModelYear')),
                ('zev_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.VehicleClass')),
                ('zev_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ZevType')),
            ],
            options={
                'db_table': 'model_year_report_vehicle',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='ModelYearReportPreviousSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('previous_sales', models.DecimalField(decimal_places=2, max_digits=20)),
                ('model_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ModelYear')),
                ('model_year_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ModelYearReport')),
            ],
            options={
                'db_table': 'model_year_report_previous_sales',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
