# Generated by Django 3.0.7 on 2021-02-16 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20210210_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelyearreport',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='api.Organization'),
            preserve_default=False,
        ),
    ]
