# Generated by Django 3.0.7 on 2021-02-17 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_modelyearreport_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelyearreportvehicle',
            old_name='model',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='modelyearreportvehicle',
            old_name='zev_type',
            new_name='vehicle_zev_type',
        ),
        migrations.AddField(
            model_name='modelyearreportvehicle',
            name='model_year_report',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='api.ModelYearReport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelyearreportvehicle',
            name='zev_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.CreditClass'),
        ),
    ]
