# Generated by Django 3.0.7 on 2021-03-01 19:41

import db_comments.model_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_vehicle_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSubmissionContentReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('reason', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sales_submission_content_reason',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.AddField(
            model_name='salessubmissioncontent',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
