# Generated by Django 3.0.7 on 2021-03-24 21:01

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_auto_20210301_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelYearReportCreditOffset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('credit_a_offset_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('credit_b_offset_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('model_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ModelYear')),
                ('model_year_report', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_year_report_credit_offset', to='api.ModelYearReport')),
            ],
            options={
                'db_table': 'model_year_report_credit_offset',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
