# Generated by Django 3.0.7 on 2021-05-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_modelyearreportcomplianceobligation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelyearreport',
            name='ldv_sales',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='modelyearreportprevioussales',
            name='previous_sales',
            field=models.IntegerField(),
        ),
    ]
