# Generated by Django 3.0.14 on 2021-05-14 22:18

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_modelyearreportcomplianceobligation'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelyearreportmake',
            name='from_gov',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelyearreportprevioussales',
            name='from_gov',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ModelYearReportAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('number_of_credits', models.IntegerField()),
                ('is_reduction', models.BooleanField(default=False)),
                ('credit_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_year_report_adjustments', to='api.CreditClass')),
                ('model_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_year_report_adjustments', to='api.ModelYear')),
                ('model_year_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_year_report_adjustments', to='api.ModelYearReport')),
            ],
            options={
                'db_table': 'model_year_report_adjustment',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
