# Generated by Django 3.0.3 on 2021-05-21 15:50

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20210519_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelYearReportAssessmentDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('description', models.CharField(blank=True, db_column='assessment_description', max_length=4000, null=True)),
            ],
            options={
                'db_table': 'model_year_report_assessment_descriptions',
                'ordering': ['create_timestamp'],
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='ModelYearReportAssessmentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('to_director', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, db_column='assessment_comment', max_length=4000, null=True)),
                ('model_year_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_year_report_assessment_comments', to='api.ModelYearReport')),
            ],
            options={
                'db_table': 'model_year_report_assessment_comment',
                'ordering': ['create_timestamp'],
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='ModelYearReportAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('penalty', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('model_year_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_year_report_assessment', to='api.ModelYearReport')),
                ('model_year_report_assessment_description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.ModelYearReportAssessmentDescriptions')),
            ],
            options={
                'db_table': 'model_year_report_assessment',
                'ordering': ['create_timestamp'],
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
