# Generated by Django 3.0.14 on 2021-05-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20210519_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelyearreport',
            name='ldv_sales',
        ),
    ]
