# Generated by Django 3.0.3 on 2021-05-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_organizationldvsales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelyearreportassessmentdescriptions',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='modelyearreportassessmentdescriptions',
            name='display_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
