# Generated by Django 3.0.14 on 2021-06-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_auto_20210531_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelyearreport',
            name='credit_reduction_selection',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
