# Generated by Django 3.0.7 on 2021-06-24 17:04

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_modelyearreport_credit_reduction_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelYearReportCreditTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('credit_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_year_report_credit_transaction', to='api.CreditTransaction')),
                ('model_year_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_year_report_credit_transaction', to='api.ModelYearReport')),
            ],
            options={
                'db_table': 'model_year_report_credit_transaction',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
