# Generated by Django 3.0.7 on 2021-07-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_modelyearreportcredittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelyearreportcomplianceobligation',
            name='from_gov',
            field=models.BooleanField(default=False),
        ),
    ]
