# Generated by Django 3.1.12 on 2021-07-07 18:10

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_modelyearreportcomplianceobligation_from_gov'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDeficits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('credit_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('credit_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.creditclass')),
                ('model_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.modelyear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.organization')),
            ],
            options={
                'db_table': 'organization_deficits',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
