# Generated by Django 3.0.3 on 2021-07-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_creditagreement_creditagreementattachment_creditagreementcomment_creditagreementcontent_creditagreem'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditagreement',
            name='optional_agreement_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
