# Generated by Django 3.0.7 on 2021-08-06 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_auto_20210729_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
