# Generated by Django 3.0.7 on 2021-08-05 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_auto_20210729_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 13, 38, 38, 22422)),
        ),
    ]
