# Generated by Django 3.0.7 on 2021-08-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_auto_20210806_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessubmissioncomment',
            name='to_govt',
            field=models.BooleanField(default=False),
        ),
    ]
