# Generated by Django 3.1.12 on 2021-08-12 16:25

import api.models.supplemental_report_statuses
import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_salessubmissioncomment_to_govt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('status', enumfields.fields.EnumField(default='DRAFT', enum=api.models.supplemental_report_statuses.SupplementalReportStatuses, max_length=20)),
                ('model_year_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.modelyearreport')),
            ],
            options={
                'db_table': 'supplemental_report',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
