# Generated by Django 3.1.12 on 2021-08-12 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_supplementalreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementalreport',
            name='model_year_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplemental_report', to='api.modelyearreport'),
        ),
    ]
