# Generated by Django 3.1.12 on 2021-08-12 22:07

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_auto_20210812_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementalReportSupplierInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('supplemental_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplemental_report_supplier_information', to='api.supplementalreport')),
            ],
            options={
                'db_table': 'supplemental_report_supplier_information',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='SupplementalReportSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('sales', models.IntegerField(null=True)),
                ('make', models.CharField(blank=True, max_length=250, null=True)),
                ('model_name', models.CharField(blank=True, max_length=250, null=True)),
                ('range', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('model_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.modelyear')),
                ('model_year_report_vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.modelyearreportvehicle')),
                ('supplemental_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplemental_report_sales', to='api.supplementalreport')),
                ('vehicle_zev_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.zevtype')),
                ('zev_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.creditclass')),
            ],
            options={
                'db_table': 'supplemental_report_sales',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
