# Generated by Django 3.1.12 on 2021-08-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_supplementalreportcreditactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplementalreportcreditactivity',
            name='ldv_sales',
        ),
        migrations.AddField(
            model_name='supplementalreport',
            name='ldv_sales',
            field=models.IntegerField(null=True),
        ),
    ]
