# Generated by Django 3.0.3 on 2021-08-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_auto_20210816_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementalreportsales',
            name='model_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='supplementalreportsales',
            name='vehicle_zev_type',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='supplementalreportsales',
            name='zev_class',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
