# Generated by Django 3.0.3 on 2021-08-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20210819_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementalreportsales',
            name='range',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplementalreportsales',
            name='sales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
