# Generated by Django 3.0.3 on 2021-08-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_supplementalreportattachment'),
        ('api', '0124_auto_20210819_1148'),
    ]

    operations = [
    ]
