# Generated by Django 3.1.12 on 2021-08-25 21:16

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_auto_20210824_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementalReportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('to_govt', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=4000, null=True)),
                ('supplemental_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplemental_report_comment', to='api.supplementalreport')),
            ],
            options={
                'db_table': 'supplemental_report_comment',
                'ordering': ['create_timestamp'],
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
