# Generated by Django 3.0.3 on 2021-08-30 18:26

import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_supplementalreportcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementalReportAssessmentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('to_director', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, db_column='assessment_comment', max_length=4000, null=True)),
                ('supplemental_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplemental_report_assessment_comments', to='api.SupplementalReport')),
            ],
            options={
                'db_table': 'supplemental_report_assessment_comment',
                'ordering': ['create_timestamp'],
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.CreateModel(
            name='SupplementalReportAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('penalty', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('supplemental_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplemental_assessment', to='api.SupplementalReport')),
                ('supplemental_report_assessment_description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.ModelYearReportAssessmentDescriptions')),
            ],
            options={
                'db_table': 'supplemental_report_assessment',
                'ordering': ['create_timestamp'],
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
