# Generated by Django 3.1.12 on 2021-09-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_supplementalreportassessment_supplementalreportassessmentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementalreport',
            name='supplemental_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
