# Generated by Django 3.1.12 on 2021-09-16 17:25

import api.models.model_year_report_statuses
import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_creditagreement_model_year_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementalReportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('validation_status', enumfields.fields.EnumField(default='DRAFT', enum=api.models.model_year_report_statuses.ModelYearReportStatuses, max_length=20)),
                ('supplemental_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplemental_report_history', to='api.supplementalreport')),
            ],
            options={
                'db_table': 'supplemental_report_history',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
    ]
