# Generated by Django 3.1.12 on 2021-10-01 22:17

import api.models.model_year_report_statuses
import db_comments.model_mixins
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_supplementalreporthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplementalreport',
            name='status',
            field=enumfields.fields.EnumField(default='DRAFT', enum=api.models.model_year_report_statuses.ModelYearReportStatuses, max_length=20),
        ),
        migrations.CreateModel(
            name='IcbcSnapshotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('vin', models.CharField(db_index=True, max_length=20, unique=True)),
                ('make', models.CharField(db_index=True, max_length=250)),
                ('model_name', models.CharField(db_index=True, max_length=250)),
                ('model_year', models.CharField(max_length=250)),
                ('upload_date', models.DateField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icbc_snapshot', to='api.salessubmission')),
            ],
            options={
                'db_table': 'icbc_snapshot_data',
            },
            bases=(models.Model, db_comments.model_mixins.DBComments),
        ),
        migrations.AddField(
            model_name='recordofsale',
            name='icbc_snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.icbcsnapshotdata'),
        ),
    ]
