# Generated by Django 3.1.12 on 2021-10-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_auto_20211001_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessubmission',
            name='part_of_model_year_report',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
