# Generated by Django 3.1.12 on 2022-08-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_salessubmission_part_of_model_year_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icbcsnapshotdata',
            name='vin',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
