# Generated by Django 3.1.12 on 2022-09-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_auto_20220818_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditagreementcontent',
            name='number_of_credits',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
