# Generated by Django 3.1.12 on 2022-10-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_auto_20220908_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementalreportsales',
            name='supplemental_origin_zev_sale_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
