# Generated by Django 3.1.12 on 2022-11-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_supplementalreportsales_supplemental_origin_zev_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='icbcuploaddate',
            name='filename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
