# Generated by Django 3.1.12 on 2023-01-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_icbcuploaddate_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='keycloak_user_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
