from enum import Enum, unique


@unique
class CreditTransferStatuses(Enum):
    DRAFT = 'DRAFT'
    SUBMITTED = 'SUBMITTED'
    APPROVED = 'APPROVED'
    DISAPPROVED = 'DISAPPROVED'
    RECOMMEND_APPROVAL = 'RECOMMEND_APPROVAL'
    RECOMMEND_REJECTION = 'RECOMMEND_REJECTION'
    VALIDATED = 'VALIDATED'
    RESCIND_PRE_APPROVAL = 'RESCIND_PRE_APPROVAL'
    RESCINDED = 'RESCINDED'
    REJECTED = 'REJECTED'
    DELETED = 'DELETED'
