spilo:

  replicaCount: 3

  credentials:
    useExistingSecret: true
    existingSecret:
      name: zeva-patroni-admin
      superuserKey: password-superuser
      adminKey: password-admin
      standbyKey: password-standby

  continuousArchive:
    enabled: true
    scheduleCronJob: "0 */3 * * *"
    retainBackups: 10
    storage: s3
    s3:
      bucket: zevapr
      secretName: zeva-db-backup-s3

  shipLogs:
    enabled: false
#    s3:
#      bucket: s3://zevapr
#      shipSchedule: 0 7 * * *

  persistentVolume:
    size: 4Gi
    storageClass: netapp-block-standard

  resources:
    limits:
      cpu: 360m
      memory: 400Mi
    requests:
      cpu: 180m
      memory: 200Mi  

  podDisruptionBudget:
    enabled: false

  probes:
    liveness:
      enabled: false
    readiness:
      enabled: true 
      initialDelaySeconds: 60
      failureThreshold: 20         

