spilo:

  replicaCount: 2

  credentials:
    useExistingSecret: true
    existingSecret:
      name: zeva-patroni-admin
      superuserKey: password-superuser
      adminKey: password-admin
      standbyKey: password-standby

  continuousArchive:
    enabled: true
    scheduleCronJob: "0 */3 * * *"
    retainBackups: 3
    storage: s3
    s3:
      bucket: zevadv/postgresbackup
      secretName: zeva-db-backup-s3

  shipLogs:
    enabled: false

  persistentVolume:
    size: 2Gi
    storageClass: netapp-block-standard

  resources:
    limits:
      cpu: 120m
      memory: 400Mi
    requests:
      cpu: 60m
      memory: 200Mi  

  podDisruptionBudget:
    enabled: false

  probes:
    liveness:
      enabled: false
    readiness:
      enabled: true 
      initialDelaySeconds: 60
      failureThreshold: 20         