# install spilo for specific pr on dev
# helm -n e52f12-dev install zeva-spilo-dev-1513 . -f ./values-dev-pr.yaml
spilo:
  replicaCount: 1

  credentials:
    useExistingSecret: true
    existingSecret:
      name: zeva-patroni-admin
      superuserKey: password-superuser
      adminKey: password-admin
      standbyKey: password-standby

  continuousArchive:
    enabled: false
    scheduleCronJob: "0 */3 * * *"
    retainBackups: 3
    storage: s3
    s3:
      bucket: zevadv/postgresbackup
      secretName: zeva-db-backup-s3

  shipLogs:
    enabled: false

  persistentVolume:
    size: 1Gi
    storageClass: netapp-block-standard

  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 1Gi

  podDisruptionBudget:
    enabled: false

  probes:
    liveness:
      enabled: false
    readiness:
      enabled: true
      initialDelaySeconds: 60
      failureThreshold: 20
