---
kind: Template
apiVersion: v1
labels:
  template: zeva-postgresql-persistent-template
metadata:
  name: postgresql-dc
  creationTimestamp:
parameters:
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment Name
    required: true
  - name: CPU_REQUEST
    displayName: Requested CPU
    description: Requested CPU
    required: true
  - name: CPU_LIMIT
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
  - name: DB_PVC_SIZE
    value: 5G
    displayName: PVC Size
    description: PVC Size
    required: true
  - name: NFS_DB_BACKUP_NAME
    displayName: NFS databse backup_name
    description: NFS databse backup_name
    required: true
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: postgresql
      annotations:
        template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
      labels:
        name: postgresql
        app: zeva
        role: postgresql
        env: ${ENV_NAME}
    spec:
      ports:
        - name: postgresql
          protocol: TCP
          port: 5432
          targetPort: 5432
      selector:
        name: postgresql
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: postgresql
      annotations:
        volume.beta.kubernetes.io/storage-class: netapp-block-standard
        template.openshift.io.bcgov/create: 'true'
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "${DB_PVC_SIZE}"
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
      name: postgresql
      labels:
        name: postgresql
        app: zeva
        role: postgresql
        env: ${ENV_NAME}
    spec:
      replicas: 1
      strategy:
        type: Recreate
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: false
            containerNames:
              - postgresql
            from:
              kind: ImageStreamTag
              namespace: openshift
              name: postgresql:10
        - type: ConfigChange
      test: false
      selector:
        name: postgresql
      template:
        metadata:
          creationTimestamp:
          labels:
            name: postgresql
        spec:
          volumes:
            - name: postgresql-data
              persistentVolumeClaim:
                claimName: postgresql
            - name: postgresql-backup
              persistentVolumeClaim:
                claimName: ${NFS_DB_BACKUP_NAME}
          containers:
            - name: postgresql
              image: " "
              ports:
                - containerPort: 5432
                  protocol: TCP
              env:
                - name: POSTGRESQL_DATABASE
                  value: zeva
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: zeva-postgresql
                      key: DATABASE_USER
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: zeva-postgresql
                      key: DATABASE_PASSWORD
              resources:
                request:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
              volumeMounts:
                - name: postgresql-data
                  mountPath: "/var/lib/pgsql/data"
                - mountPath: /postgresql-backup
                  name: postgresql-backup
                  subPath: postgresql-backup
              readinessProbe:
                tcpSocket:
                  port: 5432
                initialDelaySeconds: 25
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              livenessProbe:
                exec:
                  command:
                    - "/bin/sh"
                    - "-i"
                    - "-c"
                    - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d zeva -c 'SELECT 1'
                initialDelaySeconds: 30
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
              securityContext:
                capabilities: {}
                privileged: false
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
    status: {}
