apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: schemaspy
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the schemaspy image
    creationTimestamp: null
    name: schemaspy
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: schemaspy
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: schemaspy:latest
        namspace: tbiwaq-tools
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/bcgov/SchemaSpy.git
      type: Git
    strategy:
      dockerStrategy: {}
      type: Docker
    triggers:
    - type: ConfigChange
  status:
    lastVersion: 0
