---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: schemaspy-dc-release
  creationTimestamp:
parameters:
  - name: ENV_NAME
    displayName: Environment name
    description: 'Valid values: dev, test and prod'
    required: true
  - name: RELEASE_NUMBER
    displayName: Database Release Number
    description: This is same as application release number specified for pipeline.
    required: true
objects:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: schemaspy-public
      creationTimestamp:
      annotations:
        description: Defines how to deploy the container.
    spec:
      strategy:
        type: Recreate
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        activeDeadlineSeconds: 800
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - schemaspy-public
            from:
              kind: ImageStreamTag
              namespace: tbiwaq-tools
              name: schemaspy:prod
            lastTriggeredImage:
        - type: ConfigChange
      replicas: 1
      test: false
      selector:
        name: schemaspy-public
      template:
        metadata:
          name: schemaspy-public
          creationTimestamp:
          labels:
            name: schemaspy-public
        spec:
          containers:
            - name: schemaspy-public
              image:
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: DATABASE_SERVICE_NAME
                  value: postgresql
                - name: POSTGRESQL_DATABASE
                  value: zeva
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: zeva-postgresql
                      key: DATABASE_USER
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: zeva-postgresql
                      key: DATABASE_PASSWORD
                - name: SCHEMASPY_ARGUMENTS
                  value: -desc zeva-${RELEASE_NUMBER}
              resources:
                limits:
                  cpu: 1000m
                  memory: 6Gi
                requests:
                  cpu: 50m
                  memory: 512Mi
              livenessProbe:
                httpGet:
                  path: "/"
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 10
              readinessProbe:
                httpGet:
                  path: "/"
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 10
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
    status:
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      updatedReplicas: 0
      availableReplicas: 0
      unavailableReplicas: 0
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: schemaspy-audit
      creationTimestamp:
      annotations:
        description: Defines how to deploy the container.
    spec:
      strategy:
        type: Recreate
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        activeDeadlineSeconds: 800
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - schemaspy-audit
            from:
              kind: ImageStreamTag
              namespace: tbiwaq-tools
              name: schemaspy:prod
            lastTriggeredImage:
        - type: ConfigChange
      replicas: 1
      test: false
      selector:
        name: schemaspy-audit
      template:
        metadata:
          name: schemaspy-audit
          creationTimestamp:
          labels:
            name: schemaspy-audit
        spec:
          containers:
            - name: schemaspy-audit
              image:
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: DATABASE_SERVICE_NAME
                  value: postgresql
                - name: POSTGRESQL_DATABASE
                  value: zeva
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: zeva-postgresql
                      key: DATABASE_USER
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: zeva-postgresql
                      key: DATABASE_PASSWORD
                - name: DATABASE_SCHEMA
                  value: zeva_audit
                - name: SCHEMASPY_ARGUMENTS
                  value: -desc zeva-${RELEASE_NUMBER}
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 2Gi
              livenessProbe:
                httpGet:
                  path: "/"
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 90
                timeoutSeconds: 3
                periodSeconds: 20
                successThreshold: 1
                failureThreshold: 10
              readinessProbe:
                httpGet:
                  path: "/"
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 90
                timeoutSeconds: 3
                periodSeconds: 20
                successThreshold: 1
                failureThreshold: 10
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
    status:
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      updatedReplicas: 0
      availableReplicas: 0
      unavailableReplicas: 0
  - kind: Service
    apiVersion: v1
    metadata:
      name: schemaspy-public
      creationTimestamp:
      annotations:
        description: Exposes and load balances the application pods
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        name: schemaspy-public
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: Service
    apiVersion: v1
    metadata:
      name: schemaspy-audit
      creationTimestamp:
      annotations:
        description: Exposes and load balances the application pods
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        name: schemaspy-audit
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: schemaspy-public
      creationTimestamp:
    spec:
      host: ${ENV_NAME}-zeva-schemaspy-public.pathfinder.gov.bc.ca
      to:
        kind: Service
        name: schemaspy-public
        weight: 100
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Allow
      wildcardPolicy: None
    status:
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: schemaspy-audit
      creationTimestamp:
    spec:
      host: ${ENV_NAME}-zeva-schemaspy-audit.pathfinder.gov.bc.ca
      to:
        kind: Service
        name: schemaspy-audit
        weight: 100
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Allow
      wildcardPolicy: None
    status:
