apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: zeva-backend-bc
parameters:
  - name: NAME
    displayName:
    description: the module name entered when run yo bcdk:pipeline, which is zeva
    required: true
  - name: SUFFIX
    displayName:
    description: sample is -pr-0
    required: true
  - name: VERSION
    displayName:
    description:  image tag name for output
    required: true
  - name: GIT_URL
    displayName:
    description: zeva repo
    required: true
  - name: GIT_REF
    displayName:
    description: zeva branch name of the pr
    required: true
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: Keeps track of changes in the backend image
      creationTimestamp: null
      name: ${NAME}-python
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: Keeps track of changes in the backend image
      labels:
        shared: "true"
      creationTimestamp: null
      name: ${NAME}-backend
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      annotations:
        description: Defines how to build the application
      creationTimestamp: null
      name: ${NAME}-backend${SUFFIX}
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-backend:${VERSION}
      postCommit: {}
      resources:
        limits:
          cpu: 2000m
          memory: 2G
        requests:
          cpu: 500m
          memory: 200M
      runPolicy: SerialLatestOnly
      source:
        contextDir: backend
        git:
          ref: ${GIT_REF}
          uri: ${GIT_URL}
        type: Git
      strategy:
        sourceStrategy:
          env:
          - name: PIP_INDEX_URL
          from:
            kind: ImageStreamTag
            name: python:3.6-1-63
        type: Source
      triggers:
      - imageChange: {}
        type: ImageChange
      - type: ConfigChange
    status:
      lastVersion: 0
