## The regular exopression really should be [a-zA-Z0-9!_=$^()+]{50}
## but it doesn't work for oOpenshift
apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: DJANGO_SECRET
  description: "Cookie used for authentication of cluster nodes"
  from: "[a-zA-Z0-9]{50}"
  generate: expression
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: template.django-secret
  stringData:
    DJANGO_SECRET_KEY: ${DJANGO_SECRET}