from collections import namedtuple

Authority = namedtuple('Authority', ('root', 'group', 'role', 'description'))

REQUIRED_AUTHORITIES = [
    Authority(None, 'IDIR', 'Government', 'Can see government-specific resources'),
    Authority(None, 'BCeID', 'Vehicle Supplier', 'Can see vehicle-supplier-specific resources'),
    Authority('IDIR', 'Administrator', 'View Dashboard', 'can view dashboard tasks and reports filtered by user role'),
    Authority('IDIR', 'Administrator', 'View Roles and Permissions', 'can view roles and permissions information'),
    Authority('IDIR', 'Administrator', 'View Organizations', 'can view organization information'),
    Authority('IDIR', 'Administrator', 'Create Organizations', 'can create new organizations'),
    Authority('IDIR', 'Administrator', 'Edit Organizations', 'can edit organization information'),
    Authority('IDIR', 'Administrator', 'Delete Organizations', 'can hide/disable organizations'),
    Authority('IDIR', 'Administrator', 'View Users', 'can view user information'),
    Authority('IDIR', 'Administrator', 'Create Users', 'can create new users'),
    Authority('IDIR', 'Administrator', 'Edit Users', 'can edit user information'),
    Authority('IDIR', 'Administrator', 'Delete Users', 'can hide/disable users'),
    Authority('IDIR', 'Administrator', 'Assign IDIR Roles', 'can assign roles to government (IDIR) users'),
    Authority('IDIR', 'Administrator', 'Assign BCeID Roles', 'can assign roles to external (BCeID) users'),
    Authority('IDIR', 'Director', 'View Dashboard', 'can view dashboard tasks and reports filtered by user role'),
    Authority('IDIR', 'Director', 'View Organizations', 'can view organization information'),
    Authority('IDIR', 'Director', 'View Users', 'can view user information'),
    Authority('IDIR', 'Director', 'View ZEV', 'can view ZEV model information'),
    Authority('IDIR', 'Director', 'View Sales', 'can view sales submissions for early credits'),
    Authority('IDIR', 'Director', 'Sign Sales', 'can approve and sign a sales submission for early credits'),
    Authority('IDIR', 'Director', 'Decline Sales', 'can decline to approve a sales submission for early credits'),
    Authority('IDIR', 'Director', 'View Credit Transfers', 'can view credit transfers'),
    Authority('IDIR', 'Director', 'Sign Credit Transfers', 'can approve and sign a credit transfers'),
    Authority('IDIR', 'Director', 'Decline Credit Transfers', 'can decline to approve a credit transfers'),
    Authority('IDIR', 'Director', 'View Compliance Reports', 'can view compliance reports'),
    Authority('IDIR', 'Director', 'Sign Compliance Report', 'can accept and sign a compliance report'),
    Authority('IDIR', 'Director', 'Reject Compliance Report', 'can reject a compliance report'),
    Authority('IDIR', 'Director', 'View Initiative Agreements', 'can view initiative agreements'),
    Authority('IDIR', 'Director', 'Sign Initiative Agreements', 'can approve and sign an initiative agreements'),
    Authority('IDIR', 'Director', 'Decline Initiative Agreements', 'can decline to approve an initiative agreements'),
    Authority('IDIR', 'Director', 'View Purchase Requests', 'can view credit purchase requests'),
    Authority('IDIR', 'Director', 'Sign Purchase Requests', 'can approve and sign a purchase requests'),
    Authority('IDIR', 'Director', 'Decline Purchase Requests', 'can decline to approve a purchase requests'),
    Authority('IDIR', 'Director', 'View File Submissions', 'can view and download files that have been uploaded'),
    Authority('IDIR', 'Engineer/Analyst', 'View Dashboard',
              'can view dashboard tasks and reports filtered by user role'),
    Authority('IDIR', 'Engineer/Analyst', 'View ZEV', 'can view ZEV model information'),
    Authority('IDIR', 'Engineer/Analyst', 'Create ZEV', 'can create new ZEV models'),
    Authority('IDIR', 'Engineer/Analyst', 'Edit ZEV', 'can edit ZEV model information'),
    Authority('IDIR', 'Engineer/Analyst', 'Delete ZEV', 'can hide/disable ZEV models'),
    Authority('IDIR', 'Engineer/Analyst', 'Validate ZEV', 'can validate/unvalidate ZEV models'),
    Authority('IDIR', 'Engineer/Analyst', 'View Sales', 'can view sales submissions for early credits'),
    Authority('IDIR', 'Engineer/Analyst', 'Create Sales', 'can create a new sales submission for early credits'),
    Authority('IDIR', 'Engineer/Analyst', 'Edit Sales', 'can edit sales submission for early credits'),
    Authority('IDIR', 'Engineer/Analyst', 'Delete Sales', 'can hide/disable sales submission for early credits'),
    Authority('IDIR', 'Engineer/Analyst', 'Recommend Sales',
              'can recommend approval or rejection of a sales submission for early credits'),
    Authority('IDIR', 'Engineer/Analyst', 'View Credit Transfers', 'can view credit transfer proposals'),
    Authority('IDIR', 'Engineer/Analyst', 'Create Credit Transfer', 'can create a new credit transfer proposal'),
    Authority('IDIR', 'Engineer/Analyst', 'Edit Credit Transfers', 'can edit credit transfer proposals'),
    Authority('IDIR', 'Engineer/Analyst', 'Delete Credit Transfers', 'can hide/disable credit transfer proposals'),
    Authority('IDIR', 'Engineer/Analyst', 'Recommend Credit Transfer',
              'can recommend approval or rejection of a credit transfer proposal'),
    Authority('IDIR', 'Engineer/Analyst', 'View Compliance Reports', 'can view compliance reports'),
    Authority('IDIR', 'Engineer/Analyst', 'Create Compliance Reports', 'can create a new compliance report'),
    Authority('IDIR', 'Engineer/Analyst', 'Edit Compliance Reports', 'can edit compliance reports'),
    Authority('IDIR', 'Engineer/Analyst', 'Delete Compliance Reports', 'can hide/disable compliance reports'),
    Authority('IDIR', 'Engineer/Analyst', 'Recommend Compliance Report',
              'can recommend acceptance or rejection of a compliance report'),
    Authority('IDIR', 'Engineer/Analyst', 'View Initiative Agreements', 'can view initiative agreements'),
    Authority('IDIR', 'Engineer/Analyst', 'Create Initiative Agreements', 'can create a new initiative agreement'),
    Authority('IDIR', 'Engineer/Analyst', 'Edit Initiative Agreements', 'can edit initiative agreements'),
    Authority('IDIR', 'Engineer/Analyst', 'Delete Initiative Agreements', 'can hide/disable initiative agreements'),
    Authority('IDIR', 'Engineer/Analyst', 'Recommend Initiative Agreements',
              'can recommend approval or rejection of an initiative agreements'),
    Authority('IDIR', 'Engineer/Analyst', 'View Purchase Requests', 'can view credit purchase requests'),
    Authority('IDIR', 'Engineer/Analyst', 'Create Purchase Requests', 'can create a new purchase request'),
    Authority('IDIR', 'Engineer/Analyst', 'Edit Purchase Requests', 'can edit purchase requests'),
    Authority('IDIR', 'Engineer/Analyst', 'Delete Purchase Requests', 'can hide/disable purchase requests'),
    Authority('IDIR', 'Engineer/Analyst', 'Recommend Purchase Requests',
              'can recommend approval or rejection of a purchase requests'),
    Authority('IDIR', 'Engineer/Analyst', 'View File Submissions',
              'can view and download files that have been uploaded'),
    Authority('BCeID', 'Organization Administrator', 'View Dashboard',
              'can view dashboard tasks and reports filtered by user role'),
    Authority('BCeID', 'Organization Administrator', 'View Roles and Permissions',
              'can view roles and permissions information'),
    Authority('BCeID', 'Organization Administrator', 'View Organization Information',
              'can view organization information'),
    Authority('BCeID', 'Organization Administrator', 'Edit Organization Information',
              'can edit organization information'),
    Authority('BCeID', 'Organization Administrator', 'View Users', 'can view user information'),
    Authority('BCeID', 'Organization Administrator', 'Create Users', 'can create new users'),
    Authority('BCeID', 'Organization Administrator', 'Edit Users', 'can edit user information'),
    Authority('BCeID', 'Organization Administrator', 'Delete Users', 'can delete/disable users'),
    Authority('BCeID', 'Organization Administrator', 'Assign BCeID Roles',
              'can assign roles to external (BCeID) users'),
    Authority('BCeID', 'Signing Authority', 'View Dashboard',
              'can view dashboard tasks and reports filtered by user role'),
    Authority('BCeID', 'Signing Authority', 'View Organization Information', 'can view organization information'),
    Authority('BCeID', 'Signing Authority', 'Submit ZEV', 'can submit new ZEV models to be validated by government'),
    Authority('BCeID', 'Signing Authority', 'Submit Sales', 'can submit a sales submission for early credits'),
    Authority('BCeID', 'Signing Authority', 'Submit Credit Transfer Proposal',
              'can sign and submit a credit transfer proposal for government approval'),
    Authority('BCeID', 'Signing Authority', 'Submit Compliance Report',
              'can sign and submit a compliance report for government acceptance'),
    Authority('BCeID', 'Signing Authority', 'Submit Initiative Agreements',
              'can sign and submit an initiative agreement for government approval'),
    Authority('BCeID', 'Signing Authority', 'Submit Purchase Requests',
              'can sign and submit a purchase requests for government approval'),
    Authority('BCeID', 'Manage ZEV', 'View Dashboard', 'can view dashboard tasks and reports filtered by user role'),
    Authority('BCeID', 'Manage ZEV', 'View Organization Information', 'can view organization information'),
    Authority('BCeID', 'Manage ZEV', 'View ZEV', 'can view ZEV model information'),
    Authority('BCeID', 'Manage ZEV', 'Create ZEV', 'can create new ZEV models'),
    Authority('BCeID', 'Manage ZEV', 'Edit ZEV', 'can edit ZEV model information'),
    Authority('BCeID', 'Manage ZEV', 'Delete ZEV', 'can hide/disable ZEV models'),
]


def roles_in_group(group_names: []):
    matched_roles = []

    for group in group_names:
        for authority in REQUIRED_AUTHORITIES:
            if authority.group == group:
                matched_roles.append(authority.role)

    return list(set(matched_roles))
