# Stage 1: Use yarn to build the app
FROM artifacts.developer.gov.bc.ca/docker-remote/node:20.18.1 as builder
WORKDIR /usr/src/app
COPY ./ ./
RUN npm install -g npm@9.1.1 \
    && npm install --omit=dev \
    && npm install -D webpack webpack-cli
RUN yes | npm run dist

# Stage 2: Copy the JS React SPA into the Nginx HTML directory
FROM docker.io/nginxinc/nginx-unprivileged:1.29.1-alpine
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /usr/src/app/public/build /app

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
