apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: zeva-frontend-configs
parameters:
  - name: NAME
    displayName: null
    description: 'the module name entered when run yo bcdk:pipeline, which is zeva'
    value: zeva
    required: true
  - name: SUFFIX
    displayName: null
    description: sample is -dev-97
    value: ''
    required: true
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      creationTimestamp: null
      name: ${NAME}-frontend-config${SUFFIX}
    data:
      features.js: |
        window.zeva_config = {
          'credit_transfers.enabled': false,
          'credit_transactions.enabled': true,
          'initiative_agreements.enabled': false,
          'model_year_report.enabled': false,
          'purchase_requests.enabled': false,
          'roles.enabled': false
        };