apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: zeva-backend-dc-unittest
parameters:
  - name: NAME
    displayName: null
    description: 'the module name entered when run yo bcdk:pipeline, which is zeva'
    required: true
  - name: SUFFIX
    displayName: null
    description: sample is -dev-97
    required: true
  - name: VERSION
    displayName: null
    description: image tag name for output
    required: true
  - name: ENV_NAME
    value: dev
    displayName: Environment name
    description: 'Environment name, dev, test and prod'
    required: true
  - name: BACKEND_HOST_NAME
    displayName: Host name for route
    description: Host name for route
    required: true    
  - name: RABBITMQ_CLUSTER_NAME
    displayName: rabbitmq cluser name
    description: rabbitmq cluser name
    required: true        
  - name: CPU_REQUEST
    displayName: Requested CPU
    description: Requested CPU
    required: true
  - name: CPU_LIMIT
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
  - name: HEALTH_CHECK_DELAY
    value: '150'
    displayName: Memory upper limit
    description: Memory upper limit
    required: true    
  - name: REPLICAS
    value: '1'
    required: true
  - name: DJANGO_SECRET
    description: "Cookie used for authentication of cluster nodes"
    from: "[a-zA-Z0-9]{50}"
    generate: expression    
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: ${NAME}${SUFFIX}    
      annotations: null
      name: ${NAME}-django-unittest${SUFFIX}
    stringData:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET}
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: Keeps track of changes in the backend image
      labels:
        shared: "true"        
      creationTimestamp: null
      name: '${NAME}-backend'
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ''
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      annotations:
        description: Defines how to deploy the application server
      creationTimestamp: null
      labels:
        name: backend
        app: zeva
        role: backend-unittest
        env: ${ENV_NAME}
      name: ${NAME}-backend-unittest${SUFFIX}
    spec:
      replicas: ${{REPLICAS}}
      revisionHistoryLimit: 10
      selector:
        name: ${NAME}-backend-unittest${SUFFIX}
      strategy:
        activeDeadlineSeconds: 800
        resources: {}
        type: Recreate
      template:
        metadata:
          creationTimestamp: null
          labels:
            name: ${NAME}-backend-unittest${SUFFIX}
        spec:
          initContainers:
            - name: wait-for-database
              image: toschneck/wait-for-it:latest
              command: ['sh', '-c', './wait-for-it.sh -t 0 ${NAME}-postgresql-unittest${SUFFIX}.tbiwaq-${ENV_NAME}.svc.cluster.local:5432']
          containers:
            - name: backend-unittest
              image: null
              imagePullPolicy: IfNotPresent
              env:
                - name: DATABASE_NAME
                  value: zeva
                - name: DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-postgresql-unittest${SUFFIX}
                      key: DATABASE_USER
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-postgresql-unittest${SUFFIX}
                      key: DATABASE_PASSWORD
                - name: DATABASE_ENGINE
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: database_engine
                - name: DATABASE_SERVICE_NAME
                  value: ${NAME}-postgresql-unittest${SUFFIX}
                - name: POSTGRESQL_SERVICE_HOST
                  value: ${NAME}-postgresql-unittest${SUFFIX}.tbiwaq-${SUFFIX}.svc.cluster.local
                - name: POSTGRESQL_SERVICE_PORT
                  value: '5432'
                - name: KEYCLOAK_CERTS_URL
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_certs_url
                - name: KEYCLOAK_REALM
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_realm
                - name: KEYCLOAK_REALM_URL
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_realm_url
                - name: KEYCLOAK_AUTHORITY
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_authority
                - name: KEYCLOAK_ISSUER
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_issuer
                - name: KEYCLOAK_AUDIENCE
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_audience
                - name: KEYCLOAK_CLIENT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_client_id
                - name: KEYCLOAK_SA_BASEURL
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_sa_baseurl
                - name: KEYCLOAK_SA_REALM
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_sa_realm
                - name: KEYCLOAK_SA_CLIENT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_sa_client_id
                - name: KEYCLOAK_SA_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: zeva-keycloak
                      key: KEYCLOAK_SA_CLIENT_SECRET
                - name: DJANGO_DEBUG
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: django_debug
                - name: DJANGO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-django-unittest${SUFFIX}
                      key: DJANGO_SECRET_KEY
                - name: RABBITMQ_VHOST
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: rabbitmq_vhost
                - name: RABBITMQ_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}-${RABBITMQ_CLUSTER_NAME}-secret
                      key: username
                - name: RABBITMQ_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}-${RABBITMQ_CLUSTER_NAME}-secret
                      key: password
                - name: RABBITMQ_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: rabbitmq_host
                - name: RABBITMQ_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: rabbitmq_port
                - name: EMAIL_SENDING_ENABLED
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: email_sending_enabled
                - name: EMAIL_FROM_ADDRESS
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: email_from_address
                - name: APP_CONFIG
                  value: /opt/app-root/src/gunicorn.cfg
                - name: ENV_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: env_name
                - name: MINIO_USE_SSL
                  value: 'true'
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-minio-${ENV_NAME}
                      key: MINIO_ACCESS_KEY
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-minio-${ENV_NAME}
                      key: MINIO_SECRET_KEY
                - name: MINIO_ENDPOINT
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: minio_endpoint
              livenessProbe:
                failureThreshold: 30
                tcpSocket:
                  port: 8080
                initialDelaySeconds: ${{HEALTH_CHECK_DELAY}}
                periodSeconds: 15
                successThreshold: 1
                timeoutSeconds: 3
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                failureThreshold: 30
                tcpSocket:
                  port: 8080
                initialDelaySeconds: ${{HEALTH_CHECK_DELAY}}
                periodSeconds: 15
                successThreshold: 1
                timeoutSeconds: 3
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - backend-unittest
            from:
              kind: ImageStreamTag
              name: ${NAME}-backend:${VERSION}
            lastTriggeredImage: null
          type: ImageChange
        - type: ConfigChange
    status:
      availableReplicas: 0
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      unavailableReplicas: 0
      updatedReplicas: 0
