/* global
  __APIBASE__
  __KEYCLOAK_CLIENT_ID__
  __KEYCLOAK_LOGOUT_REDIRECT_URL__
  __KEYCLOAK_REALM_NAME__
  __KEYCLOAK_URL__
  __VERSION__
*/
const CONFIG = {
  APIBASE: __APIBASE__, // injected by webpack
  KEYCLOAK: {
    CLIENT_ID: __KEYCLOAK_CLIENT_ID__,
    LOGOUT_URL: __KEYCLOAK_LOGOUT_REDIRECT_URL__,
    REALM: __KEYCLOAK_REALM_NAME__,
    URL: __KEYCLOAK_URL__,
  },
  VERSION: __VERSION__,
};

export default CONFIG;
