version: '3'

services:
    envoy:
      depends_on:
        - frontend
        - transaction_service
      build:
        context: ./envoy
        dockerfile: Dockerfile-envoy
      ports:
        - 9901:9901
        - 10000:10000
    postgres:
      image: postgres:12.0
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: zeva
        POSTGRES_USER: zeva
        POSTGRES_PASSWORD: zevadev
      ports:
        - 5432:5432
    rabbit:
        image: rabbitmq:3.7-management
        hostname: "rabbit"
        environment:
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
            - RABBITMQ_DEFAULT_VHOST=/zeva
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}]
        ports:
            - 15672:15672
            - 5672:5672
    postgres_keycloak:
        image: postgres:12.0
        volumes:
          - postgres_keycloak_data:/var/lib/postgresql/data
        environment:
          POSTGRES_DB: keycloak
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: keycloak
    keycloak:
        build:
            context: ./keycloak
            dockerfile: Dockerfile-keycloak
        command: -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/realm.json -Dkeycloak.migration.strategy=IGNORE_EXISTING
        environment:
          DB_VENDOR: POSTGRES
          DB_ADDR: postgres_keycloak
          DB_DATABASE: keycloak
          DB_USER: keycloak
          DB_PASSWORD: keycloak
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
          KEYCLOAK_LOGLEVEL: WARN
          ROOT_LOGLEVEL: WARN
        ports:
          - 8888:8080
        depends_on:
          - postgres_keycloak
    minio:
      image: minio/minio
      volumes:
        - minio_data:/export
      environment:
        MINIO_ACCESS_KEY: 296e92217fa3479aaf9cc9641fdb6e0a
        MINIO_SECRET_KEY: 778eecb24d7743b5a1b56bbf36a29d62
      ports:
        - 9000:9000
      command: "server /export"
    smtplogger:
      build:
        context: ./smtplogger
        dockerfile: Dockerfile-smtplogger
      ports:
        - 2500:2500
    transaction_service:
      build:
        dockerfile: Dockerfile
        context: ./services/transaction
      ports:
        - 10101:10101
    frontend:
      build:
        dockerfile: Dockerfile-node
        context: ./frontend
      command: >
        bash -c
        "npm install &&
        npm rebuild node-sass &&
        /wfi/wait-for-it.sh rabbit:5672 -t 14400 &&
        npm run start"
      depends_on:
        - rabbit
      ports:
        - 5001:5001
      environment:
        - RABBITMQ_VHOST=/zeva
        - RABBITMQ_USER=rabbitmq
        - RABBITMQ_PASSWORD=rabbitmq
        - RABBITMQ_HOST=rabbit
        - RABBITMQ_PORT=5672
        - KEYCLOAK_ENABLED=False
        - KEYCLOAK_AUTHORITY=http://localhost:8888/auth/realms/zeva
        - KEYCLOAK_CLIENT_ID=zeva-app
        - KEYCLOAK_REALM=http://localhost:8888/auth/realms/zeva
        - KEYCLOAK_ISSUER=http://localhost:8888/auth/realms/zeva
        - KEYCLOAK_CALLBACK_URL=http://localhost:5001/authCallback
        - KEYCLOAK_POST_LOGOUT_URL=http://localhost:5001/
        - KEYCLOAK_CERTS_URL=http://keycloak:8080/auth/realms/zeva/protocol/openid-connect/certs
      volumes:
        - node_modules:/app/node_modules
volumes:
    postgres_keycloak_data:
    postgres_data:
    minio_data:
    node_modules:
