apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 5001
      targetPort: 5001
      name: 'web'
    - port: 5002
      targetPort: 5002
      name: 'websocket-notifications'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  minReadySeconds: 20
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend
          ports:
            - containerPort: 5001
            - containerPort: 5002
          env:
            - name: KEYCLOAK_CERTS_URL
              value: 'https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/certs'
            - name: KEYCLOAK_REALM
              value: 'https://dev.loginproxy.gov.bc.ca/auth/realms/standard'
            - name: KEYCLOAK_AUTHORITY
              value: 'https://dev.loginproxy.gov.bc.ca/auth/realms/standard'
            - name: KEYCLOAK_ISSUER
              value: 'https://dev.loginproxy.gov.bc.ca/auth/realms/standard'
            - name: KEYCLOAK_URL
              value: 'https://dev.loginproxy.gov.bc.ca/auth'
            - name: KEYCLOAK_AUDIENCE
              value: 'zeva-on-gold-4543'
            - name: KEYCLOAK_CLIENT_ID
              value: 'zeva-on-gold-4543'
            - name: KEYCLOAK_REALM_NAME
              value: 'standard'
            - name: RABBITMQ_ENABLED
              value: 'False'
            - name: APIBASE
              value: 'http://localhost:10000/api'
  selector:
    matchLabels:
      app: frontend
