apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
spec:
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      name: envoy-pod
      labels:
        app: envoy
    spec:
      containers:
        - name: envoy
          image: envoy
          ports:
            - name: admin
              containerPort: 9901
            - name: http-in
              containerPort: 10000
            - name: keycloak-in
              containerPort: 8888
  selector:
    matchLabels:
      app: envoy
---
apiVersion: v1
kind: Service
metadata:
  name: entrypoint
spec:
  selector:
    app: envoy
  ports:
    - name: http-in
      port: 10000
      targetPort: 10000
    - name: admin
      port: 9901
      targetPort: 9901
    - name: keycloak-in
      port: 8888
      targetPort: 8888
