apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: envoy
spec:
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      name: envoy-pod
      labels:
        app: envoy
    spec:
      containers:
        - name: envoy
          image: envoy
          ports:
            - name: admin
              containerPort: 9901
            - name: http-in
              containerPort: 10000
            - name: keycloak-in
              containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: entrypoint
spec:
  selector:
    app: envoy
  ports:
    - name: admin
      port: 10000
      targetPort: 10000
    - name: http-in
      port: 9901
      targetPort: 9901
    - name: keycloak-in
      port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 5001
      targetPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: smtplogger
spec:
  selector:
    app: smtplogger
  ports:
    - port: 2500
      targetPort: 2500
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak
spec:
  selector:
    app: postgres-keycloak
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  minReadySeconds: 20
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend
          ports:
            - containerPort: 5001
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: golang-transaction-service
spec:
  replicas: 5
  template:
    metadata:
      name: golang-transaction-service-pod
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: transaction-service
          ports:
            - containerPort: 10101
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction-service
  ports:
    - port: 10101
      targetPort: 10101
---
apiVersion: v1
kind: Pod
metadata:
  name: smtplogger
spec:
  containers:
    - name: smtplogger
      image: smtplogger
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-keycloak
spec:
  replicas: 1
  template:
    metadata:
      name: postgres-keycloak
      labels:
        app: postgres-keycloak
    spec:
      containers:
        - name: postgresql-keycloak
          image: postgres:12.0
          env:
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: keycloak
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command: ["psql", "-w", "-U", "keycloak", "-d", "keycloak", "-c", "SELECT 1"]
            initialDelaySeconds: 15
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command: ["psql", "-w", "-U", "keycloak", "-d", "keycloak", "-c", "SELECT 1"]
            initialDelaySeconds: 45
            timeoutSeconds: 2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  template:
    metadata:
      name: keycloak
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: keycloak
          env:
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: postgres-keycloak
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              value: keycloak
            - name: DB_PASSWORD
              value: keycloak
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_PORT
              value: "5432"
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: KEYCLOAK_LOGLEVEL
              value: INFO
            - name: ROOT_LOGLEVEL
              value: FATAL
          args: ['-Dkeycloak.migration.action=import','-Dkeycloak.migration.provider=singleFile','-Dkeycloak.migration.file=/tmp/realm.json','-Dkeycloak.migration.strategy=IGNORE_EXISTING']
          ports:
            - containerPort: 8080
      initContainers:
        - name: init-psql
          image: busybox
          command: ['sh', '-c', 'until nslookup postgres-keycloak; do echo waiting for postgres; sleep 2; done;']
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgresql
          image: postgres:12.0
          env:
            - name: POSTGRES_DB
              value: zeva
            - name: POSTGRES_USER
              value: zeva
            - name: POSTGRES_PASSWORD
              value: zevadev
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command: ["psql", "-w", "-U", "zeva", "-d", "zeva", "-c", "SELECT 1"]
            initialDelaySeconds: 15
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command: ["psql", "-w", "-U", "zeva", "-d", "zeva", "-c", "SELECT 1"]
            initialDelaySeconds: 45
            timeoutSeconds: 2
