apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-keycloak
spec:
  replicas: 1
  template:
    metadata:
      name: postgres-keycloak
      labels:
        app: postgres-keycloak
    spec:
      containers:
        - name: postgresql-keycloak
          image: postgres:12.0
          env:
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: keycloak
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command: ["psql", "-w", "-U", "keycloak", "-d", "keycloak", "-c", "SELECT 1"]
            initialDelaySeconds: 15
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command: ["psql", "-w", "-U", "keycloak", "-d", "keycloak", "-c", "SELECT 1"]
            initialDelaySeconds: 45
            timeoutSeconds: 2
  selector:
    matchLabels:
      app: postgres-keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  template:
    metadata:
      name: keycloak
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: keycloak
          env:
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: postgres-keycloak
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              value: keycloak
            - name: DB_PASSWORD
              value: keycloak
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_PORT
              value: "5432"
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: KEYCLOAK_LOGLEVEL
              value: INFO
            - name: ROOT_LOGLEVEL
              value: FATAL
          args: ['-Dkeycloak.migration.action=import','-Dkeycloak.migration.provider=singleFile','-Dkeycloak.migration.file=/tmp/realm.json','-Dkeycloak.migration.strategy=IGNORE_EXISTING']
          ports:
            - containerPort: 8080
      initContainers:
        - name: init-psql-keycloak
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup postgres-keycloak; do echo waiting for postgres; sleep 5; done;']
  selector:
    matchLabels:
      app: keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak
spec:
  selector:
    app: postgres-keycloak
  ports:
    - port: 5432
      targetPort: 5432
