apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgresql
          image: postgres:12.0
          env:
            - name: POSTGRES_DB
              value: zeva
            - name: POSTGRES_USER
              value: zeva
            - name: POSTGRES_PASSWORD
              value: zevadev
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command: ["psql", "-w", "-U", "zeva", "-d", "zeva", "-c", "SELECT 1"]
            initialDelaySeconds: 15
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command: ["psql", "-w", "-U", "zeva", "-d", "zeva", "-c", "SELECT 1"]
            initialDelaySeconds: 45
            timeoutSeconds: 2
  selector:
    matchLabels:
      app: postgres
