apiVersion: v1
kind: Service
metadata:
  name: python-backend
spec:
  selector:
    app: python-backend
  ports:
    - port: 10102
      targetPort: 10102
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
spec:
  replicas: 1
  minReadySeconds: 20
  template:
    metadata:
      name: python-backend-pod
      labels:
        app: python-backend
    spec:
      containers:
        - name: python-backend
          image: python-backend
          ports:
            - containerPort: 10102
  selector:
    matchLabels:
      app: python-backend
