apiVersion: v1
kind: Service
metadata:
  name: smtplogger
spec:
  selector:
    app: smtplogger
  ports:
    - port: 2500
      targetPort: 2500
---
apiVersion: v1
kind: Pod
metadata:
  name: smtplogger
spec:
  containers:
    - name: smtplogger
      image: smtplogger
