apiVersion: v1
kind: Service
metadata:
  name: test-postgres
spec:
  selector:
    app: test-postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-postgres
spec:
  replicas: 1
  template:
    metadata:
      name: test-postgres
      labels:
        app: test-postgres
    spec:
      containers:
        - name: postgresql
          image: postgres:12.0
          env:
            - name: POSTGRES_DB
              value: zeva
            - name: POSTGRES_USER
              value: zeva
            - name: POSTGRES_PASSWORD
              value: zevadev
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command: ["psql", "-w", "-U", "zeva", "-d", "zeva", "-c", "SELECT 1"]
            initialDelaySeconds: 1
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command: ["psql", "-w", "-U", "zeva", "-d", "zeva", "-c", "SELECT 1"]
            initialDelaySeconds: 45
            timeoutSeconds: 2
  selector:
    matchLabels:
      app: test-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-test-backend
spec:
  replicas: 1
  minReadySeconds: 20
  template:
    metadata:
      name: python-test-backend-pod
      labels:
        app: python-test-backend
    spec:
      containers:
        - name: python-test-backend
          image: django-backend
          command: ["sh", "-c", "python3 manage.py test -v 3"]
          env:
            - name: DATABASE_NAME
              value: 'zeva'
            - name: DATABASE_USER
              value: 'zeva'
            - name: DATABASE_PASSWORD
              value: 'zevadev'
            - name: DATABASE_ENGINE
              value: 'postgresql'
            - name: DATABASE_SERVICE_NAME
              value: 'postgresql'
            - name: POSTGRESQL_SERVICE_HOST
              value: 'test-postgres'
            - name: POSTGRESQL_SERVICE_PORT
              value: '5432'
            - name: KEYCLOAK_CERTS_URL
              value: 'https://dev.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/certs'
            - name: KEYCLOAK_REALM
              value: 'https://dev.loginproxy.gov.bc.ca/auth/realms/standard'
            - name: KEYCLOAK_AUTHORITY
              value: 'https://dev.loginproxy.gov.bc.ca/auth/realms/standard'
            - name: KEYCLOAK_ISSUER
              value: 'https://dev.loginproxy.gov.bc.ca/auth/realms/standard'
            - name: KEYCLOAK_AUDIENCE
              value: 'zeva-on-gold-4543'
            - name: KEYCLOAK_CLIENT_ID
              value: 'zeva-on-gold-4543'
            - name: DJANGO_DEBUG
      initContainers:
        - name: init-psql
          image: busybox:1.28
          command: ['sh', '-c', 'until (nslookup test-postgres); do echo waiting for test-postgres; sleep 1; done; echo test-postgres ready; sleep 5;']
  selector:
    matchLabels:
      app: python-test-backend
