apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: envoy
    context: dockerfiles/envoy
  - image: keycloak
    context: dockerfiles/keycloak
  - image: smtplogger
    context: dockerfiles/smtplogger
  - image: transaction-service
    context: services/transaction
  - image: frontend
    context: frontend
    sync:
      infer:
      - 'src/**/*'
deploy:
  kubectl:
    manifests:
      - k8s-*
#portForward:
#    - resourceType: deployment
#      resourceName: envoy
#      port: 9901
#      localPort: 9901
#    - resourceType: deployment
#      resourceName: envoy
#      port: 10000
#      localPort: 10000
#    - resourceType: pod
#      resourceName: keycloak
#      port: 8888
#      localPort: 8888
