apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: envoy
    context: dockerfiles/envoy
  - image: keycloak
    context: dockerfiles/keycloak
  - image: smtplogger
    context: dockerfiles/smtplogger
  - image: django-backend
    context: backend
    sync:
        infer:
        - src '**/*'
  - image: frontend
    context: frontend
    sync:
      infer:
      - 'src/**/*'
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: test
    deploy:
      kubectl:
        manifests:
          - k8stests-*
