---
kind: Template
apiVersion: v1
labels:
  template: zeva-postgresql-persistent-template
metadata:
  name: postgresql-dc
  creationTimestamp:
parameters:
  - description: Username for PostgreSQL user that will be used for accessing the database.
    from: user[A-Z0-9]{3}
    generate: expression
    name: TFRS_DB_USER
    required: true
  - description: Password for the PostgreSQL connection user.
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    name: TFRS_DB_PASSWORD
    required: true
  - name: CPU_REQUEST
    displayName: Requested CPU
    description: Requested CPU
    required: true
  - name: CPU_LIMIT
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
  - name: DB_PVC_SIZE
    value: 5Gi
    displayName: PVC Size
    description: PVC Size
    required: true
  - name: DB_BACKUP_NFS_SIZE
    value: 5Gi
    displayName: DB PVC Size
    description: DB BACKUP NFS Size
    required: true
objects:
