apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: EMAIL_SERVICE_CLIENT_ID
  description: the client id for Zeva project
  required: true
- name: EMAIL_SERVICE_CLIENT_SECRET
  description: the secrete for Zeva project
  required: true
- name: CHES_AUTH_URL
  description: the authentication url to retrieve token
  required: true
- name: CHES_EMAIL_URL
  description: the email service url
  required: true
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: email-service
  stringData:
    EMAIL_SERVICE_CLIENT_ID: ${EMAIL_SERVICE_CLIENT_ID}
    EMAIL_SERVICE_CLIENT_SECRET: ${EMAIL_SERVICE_CLIENT_SECRET}
    CHES_AUTH_URL: ${CHES_AUTH_URL}
    CHES_EMAIL_URL: ${CHES_EMAIL_URL}