apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: zeva-cleanup
parameters:
  - name: LICENSE_PLATE
    description: license plate for the projec
    required: true
  - name: LOGIN_TOKEN_SECRET
    description: The secret having the login token
    required: true
objects:
  - kind: CronJob
    apiVersion: batch/v1
    metadata:
      name: zeva-cleanup
    spec:
      schedule: 0 7 * * *
      concurrencyPolicy: Forbid
      suspend: false
      jobTemplate:
        metadata:
          creationTimestamp: null
        spec:
          backoffLimit: 0
          template:
            metadata:
              creationTimestamp: null
            spec:
              containers:
                - resources:
                    limits:
                      cpu: 100m
                      memory: 100Mi
                    requests:
                      cpu: 50m
                      memory: 50Mi
                  terminationMessagePath: /dev/termination-log
                  name: oc
                  command:
                    - /bin/sh
                    - "-c"
                  env:
                    - name: LOGIN_TOKEN
                      valueFrom:
                        secretKeyRef:
                          name: ${LOGIN_TOKEN_SECRET}
                          key: token
                  imagePullPolicy: Always
                  terminationMessagePolicy: File
                  image: >-
                    image-registry.openshift-image-registry.svc:5000/${LICENSE_PLATE}-tools/zeva-cleanup:prod
                  args:
                    - >
                      date

                      oc login --token=$(LOGIN_TOKEN) --server=https://api.silver.devops.gov.bc.ca:6443

                      oc version

                      echo ""

                      echo "====> Cleaning up ${LICENSE_PLATE}-tools" 

                      echo "==========> Removing expired builds"

                      oc -n ${LICENSE_PLATE}-tools get builds | grep -E "Complete|Failed|Cancelled" | awk '{print $1}' | xargs oc -n ${LICENSE_PLATE}-tools delete build || true

                      echo "==========> Removing expired frontend and backend image tags"

                      oc -n ${LICENSE_PLATE}-tools get imagetags | grep -E "zeva-frontend|zeva-backend" | awk '{print $1}' | xargs oc -n ${LICENSE_PLATE}-tools delete imagetag || true

                      echo "==========> Removing expired pods"

                      oc -n ${LICENSE_PLATE}-tools get pods | grep -E "Completed|Error|ContainerStatusUnknown" | grep -v crunchy | grep -v spilo | awk '{print $1}' | xargs oc -n ${LICENSE_PLATE}-tools delete pod || true

                      namespaces=("${LICENSE_PLATE}-dev" "${LICENSE_PLATE}-test")

                      for namespace in "${namespaces[@]}"; do

                          echo ""

                          echo "====> Cleaning up $namespace"

                          echo "==========> Removing expired pods"

                          oc -n $namespace get pods | grep Completed | grep -v backup | awk '{print $1}' | xargs oc -n $namespace delete pod || true

                          oc -n $namespace get pods | grep -E "Error|ContainerStatusUnknown" | grep -v crunchy | grep -v spilo | grep -v backup | awk '{print $1}' | xargs oc -n $namespace delete pod || true

                          env=$(echo $namespace | awk -F '-' '{print $NF}')

                          runningBackendImageTag=$(oc -n $namespace describe dc/zeva-backend-$env | grep Triggers | grep zeva-backend | awk -F '@' '{print $2}' | awk -F ',' '{print $1}')

                          echo "==========> Removing expired backend image tags except  zeva-backend:$runningBackendImageTag"
                          
                          oc -n $namespace get imagetags | grep zeva-backend | grep -v $runningBackendImageTag | awk '{print $1}' | xargs oc -n $namespace delete imagetag || true

                          runningFrontendImageTag=$(oc -n $namespace describe dc/zeva-frontend-$env | grep Triggers | grep zeva-frontend | awk -F '@' '{print $2}' | awk -F ',' '{print $1}')

                          echo "==========> Removing expired frontend image tags except zeva-frontend:$runningFrontendImageTag"

                          oc -n $namespace get imagetags | grep zeva-frontend | grep -v $runningFrontendImageTag | awk '{print $1}' | xargs oc -n $namespace delete imagetag || true

                      done

              restartPolicy: Never
              terminationGracePeriodSeconds: 30
              dnsPolicy: ClusterFirst
              securityContext: {}
              schedulerName: default-scheduler
      successfulJobsHistoryLimit: 3
      failedJobsHistoryLimit: 1
