---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: zeva-spilo-network-policy
metadata:
  name: zeva-spilo-network-policy
parameters:
  - name: SUFFIX
    displayName: null
    description: such as -dev or -dev-1513
    required: true  
  - name: ENVIRONMENT
    displayName: null
    description: such as dev, test or prod
    required: true  
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-zeva-spilo-accepts-${ENVIRONMENT}
    spec:
      ## Allow zeva-spilo to accept communications from backend
      ## Allow zeva-spilo to accept communications from backend-mid
      ## Allow zeva-spilo to accept communications from schema-public
      ## Allow zeva-spilo to accept communications from schema-audit
      ## Allow zeva-spilo to accept communications from backup-container
      ## Allow zeva-spilo to accept communications from backup cronjob
      ## Allow zeva-spilo to accept communications from metabase from cthub
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: zeva-spilo${SUFFIX}
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/instance: zeva-backend${SUFFIX}
          ports:
            - protocol: TCP
              port: 5432       
        - from:
            - podSelector:
                matchLabels:
                  openshift.io/deployer-pod.type: hook-mid
          ports:
            - protocol: TCP
              port: 5432              
        - from:
            - podSelector:
                matchLabels:
                  name: zeva-schema-spy-public-${ENVIRONMENT}
          ports:
            - protocol: TCP
              port: 5432
        - from:
            - podSelector:
                matchLabels:
                  name: zeva-schema-spy-audit-${ENVIRONMENT}
          ports:
            - protocol: TCP
              port: 5432    
        - from:
            - podSelector:
                matchLabels:
                  name: patroni-backup
          ports:
            - protocol: TCP
              port: 5432
        - from:
            - podSelector:
                matchLabels:
                  cronjob: zeva-db-backup
          ports:
            - protocol: TCP
              port: 5432              
        - from:
            - namespaceSelector:
                matchLabels:
                  name: 30b186
                  environment: ${ENVIRONMENT}
            - podSelector:
                matchLabels:
                  app: metabase
          ports:
            - protocol: TCP
              port: 5432     
