---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: zeva-network-policy
metadata:
  name: zeva-network-policy
parameters:
  - name: SUFFIX
    displayName: null
    description: sample is -dev-97
    required: true  
  - name: ENVIRONMENT
    displayName: null
    description: such as dev, test or prod
    required: true  
objects:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-backend-accepts-frontend${SUFFIX}
    spec:
      ## Allow backend to accept communication from frontend
      podSelector:
        matchLabels:
          name: zeva-backend${SUFFIX}
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  name: zeva-frontend${SUFFIX}
          ports:
            - protocol: TCP
              port: 8080
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-patroni-accepts-backend${SUFFIX}
    spec:
      ## Allow patroni to accept communications from backend
      podSelector:
        matchLabels:
          cluster-name: patroni${SUFFIX}
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  name: zeva-backend${SUFFIX}
          ports:
            - protocol: TCP
              port: 5432
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-minio-accepts-backend${SUFFIX}
    spec:
      ## Allow minio to accept communication from backend
      podSelector:
        matchLabels:
          app: zeva-minio-${ENVIRONMENT}
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  name: zeva-backend${SUFFIX}
          ports:
            - protocol: TCP
              port: 9000                  
  ## Other Network Policies              
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-patroni-accepts-backendmid${SUFFIX}
    spec:
      ## Allow patroni to accept communications from backend mid lifecycle pod
      podSelector:
        matchLabels:
          cluster-name: patroni${SUFFIX}
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  openshift.io/deployer-pod.type: hook-mid
          ports:
            - protocol: TCP
              port: 5432
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-patroni-accepts-patroni-itself${SUFFIX}
    spec:
      ## Allow patroni to accept communications from other patroni pods
      podSelector:
        matchLabels:
          cluster-name: patroni${SUFFIX}
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  cluster-name: patroni${SUFFIX}
          ports:
            - protocol: TCP
              port: 5432    
            - protocol: TCP
              port: 8008                             
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-patroni-accepts-backup-container${SUFFIX}
    spec:
      ## Allow patroni to accept communications from backup container
      podSelector:
        matchLabels:
          cluster-name: patroni${SUFFIX}
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  name: patroni-backup
          ports:
            - protocol: TCP
              port: 5432                   
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-patroni-accepts-nagios${SUFFIX}
    spec:
      ## Allow patroni to accept communications from nagios
      podSelector:
        matchLabels:
          cluster-name: patroni${SUFFIX}
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  app: nagios
          ports:
            - protocol: TCP
              port: 5432
            - protocol: TCP
              port: 8008
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-patroni-accepts-schemaspy${SUFFIX}
    spec:
      ## Allow patroni to accept communications from schemaspy
      podSelector:
        matchLabels:
          cluster-name: patroni${SUFFIX}
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  name: schemaspy-public${SUFFIX}
          ports:
            - protocol: TCP
              port: 5432                                   
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-backend-accepts-schemaspy${SUFFIX}
    spec:
      ## Allow backend to accept communication from schemaspy
      podSelector:
        matchLabels:
          name: zeva-backend${SUFFIX}
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  name: schemaspy-public${SUFFIX}
          ports:
            - protocol: TCP
              port: 8080