---
kind: Template
apiVersion: v1
labels:
  template: zeva-nsp
metadata:
  name: zeva-nsp
  creationTimestamp:
parameters:
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment Name
    required: true
  - name: OCP_NAME
    displayName: Openshift Name
    description: Openshift Name
    required: true
objects:
  - kind: NetworkSecurityPolicy
    apiVersion: secops.${OCP_NAME}.gov.bc.ca/v1alpha1
    metadata:
      name: custom-interweb-to-frontend
    spec:
      description: |
        Allow frontend to communicate with internet.
      source:
        - - ext:network=any
      destination:
        - - app=zeva
          - role=frontend
          - env=${ENV_NAME}
  - kind: NetworkSecurityPolicy
    apiVersion: secops.${OCP_NAME}.gov.bc.ca/v1alpha1
    metadata:
      name: custom-frontend-to-backend
    spec:
      description: |
        Allow frontend to communicate with backend.
      source:
        - - app=zeva
          - role=frontend
          - env=${ENV_NAME}
      destination:
        - - app=zeva
          - role=backend
          - env=${ENV_NAME}
  - kind: NetworkSecurityPolicy
    apiVersion: secops.${OCP_NAME}.gov.bc.ca/v1alpha1
    metadata:
      name: custom-backend-to-patroni
    spec:
      description: |
        Allow backend to communicate with patroni.
      source:
        - - app=zeva
          - role=backend
          - env=${ENV_NAME}
      destination:
        - - app=zeva
          - role=patroni
          - env=${ENV_NAME}        
  - kind: NetworkSecurityPolicy
    apiVersion: secops.${OCP_NAME}.gov.bc.ca/v1alpha1
    metadata:
      name: custom-pods-to-ocp-api
    spec:
      description: |
        Allow pods to talk to the internal OCP api so deployments work.
        This only needs to be specified once per environment.
        Without this policy, pods could have PU Update error when starting container
      source:
        - - $namespace=tbiwaq-${ENV_NAME}
      destination:
        - - int:network=internal-cluster-api-endpoint
  - kind: NetworkSecurityPolicy
    apiVersion: secops.${OCP_NAME}.gov.bc.ca/v1alpha1
    metadata:
      name: custom-backend-to-keycloak
    spec:
      description: |
        Allow backend pod to communicate with keycloak
      source:
        - - app=zeva
          - role=backend
          - env=${ENV_NAME}
      destination:
        - - $namespace=devops-sso-${ENV_NAME}
          - app=sso-${ENV_NAME}
