replicaCount: 1

envName: dev
suffix: -dev-1513

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

frontendConfigMap:
  apiBase: https://zeva-backend-dev-1513.apps.silver.devops.gov.bc.ca/api
  keycloakRealm: standard
  keycloakClientId: zeva-on-gold-4543
  keycloakAuthUrl: https://dev.loginproxy.gov.bc.ca/auth
  keycloakCallbackUrl: https://zeva-dev-1513.apps.silver.devops.gov.bc.ca
  keycloakPostLogoutUrl: https://zeva-dev-1513.apps.silver.devops.gov.bc.ca
  keycloakSiteminderLogoutUrl: https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=
  complianceReportEnabled: true
  complianceCalculatorEnabled: true
  complianceRatiosEnabled: true
  creditTransfersEnabled: true
  creditTransactionsEnabled: true
  initiativeAgreementsEnabled: false
  modelYearReportEnabled: true
  purchaseRequestsEnabled: false
  notificationsEnabled: true
  rolesEnabled: true
  creditAgreementsEnabled: true
  supplementalEnabled: true

resources:
  limits:
    cpu: 80m
    memory: 120Mi
  requests:
    cpu: 40m
    memory: 60Mi

appConfigMap:
  backendHostName: zeva-backend-dev-1513.apps.silver.devops.gov.bc.ca
  databaseServiceName: zeva-spilo-dev-1513
  djangoDebug: true
  ssoName: dev.loginproxy.gov.bc.ca
  keycloakRealm: standard
  logoutHostName: logontest7.gov.bc.ca
  hostName: zeva-dev-1513.apps.silver.devops.gov.bc.ca

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  cpuAverageUtilization: 80

# the fronend host name is appConfigMap.hostName
frontendRoute: 
  create: true

livenessProbe:
  failureThreshold: 10
  initialDelaySeconds: 40
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 8080
  timeoutSeconds: 3

readinessProbe:
  failureThreshold: 10
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 8080
  timeoutSeconds: 3