replicaCount: 3

envName: prod
suffix: -prod

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

frontendConfigMap:
  apiBase: https://zeva-backend-prod.apps.silver.devops.gov.bc.ca/api
  keycloakRealm: standard
  keycloakClientId: zeva-on-gold-4543
  keycloakAuthUrl: https://loginproxy.gov.bc.ca/auth
  keycloakCallbackUrl: https://zeroemissionvehicles.gov.bc.ca
  keycloakPostLogoutUrl: https://zeroemissionvehicles.gov.bc.ca
  keycloakSiteminderLogoutUrl: https://logon7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=
  complianceReportEnabled: true
  complianceCalculatorEnabled: true
  complianceRatiosEnabled: true
  creditTransfersEnabled: true
  creditTransactionsEnabled: true
  initiativeAgreementsEnabled: false
  modelYearReportEnabled: true
  purchaseRequestsEnabled: false
  notificationsEnabled: true
  rolesEnabled: false
  creditAgreementsEnabled: true
  supplementalEnabled: false

resources:
  limits:
    cpu: 80m
    memory: 120Mi
  requests:
    cpu: 40m
    memory: 60Mi

appConfigMap:
  backendHostName: zeva-backend-prod.apps.silver.devops.gov.bc.ca
  databaseServiceName: zeva-spilo-prod
  djangoDebug: false
  ssoName: loginproxy.gov.bc.ca
  keycloakRealm: standard
  logoutHostName: logon7.gov.bc.ca
  hostName: zeroemissionvehicles.gov.bc.ca

autoscaling:
  minReplicas: 3
  maxReplicas: 5
  cpuAverageUtilization: 80

# Do not create routes for prod
frontendRoute: 
  create: false

livenessProbe:
  failureThreshold: 10
  initialDelaySeconds: 40
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 8080
  timeoutSeconds: 3

readinessProbe:
  failureThreshold: 10
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 8080
  timeoutSeconds: 3