apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: python-backend-bc
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: Keeps track of changes in the transaction-service image
      creationTimestamp: null
      name: transaction-service
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      name: transaction-service
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: transaction-service:latest
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        dockerfile: |-
          FROM golang:1.13
          WORKDIR /go/src
          RUN apt-get update
          RUN apt-get install -y git
          RUN git clone --branch devops-openshift https://github.com/bcgov/zeva.git /tmp/zeva
          RUN go get -u google.golang.org/grpc
          RUN go get -u github.com/grpc-ecosystem/go-grpc-middleware
          RUN go get -u go.uber.org/zap
          RUN mv /tmp/zeva/services/transaction/src/* /go/src/
          RUN go install transaction_service
          CMD ["transaction_service"]
        type: Dockerfile
      strategy:
        dockerStrategy:
          forcePull: false
          noCache: true
        type: Docker
      successfulBuildsHistoryLimit: 5
      triggers: []
    status:
      lastVersion: 0
