# This template only used for creating postgresql unit test database
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: zeva-postgresql-init
parameters:
  - name: NAME
    displayName:
    description: the module name entered when run yo bcdk:pipeline, which is zeva
    required: true
  - name: SUFFIX
    displayName:
    description: sample is -dev-97
    required: true
objects:
- apiVersion: v1
  data:
    create-extension.sh: |-
      psql -U postgres -q -c "ALTER USER $POSTGRESQL_USER Superuser CREATEDB"
    prepare-init-scripts: |-
      #!/bin/bash
      DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
      set -x
      mkdir -p "${APP_DATA}/src/postgresql-init"
      find -L "$DIR" -maxdepth 1 -type f -name "*.sh" -exec cp {} "${APP_DATA}/src/postgresql-init/" \;
      set +x
      exec "$@"
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: ${NAME}-postgresql-init${SUFFIX}
