apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: template.minio-secret
parameters:
  - name: MINIO_ACCESS_KEY
    description: Minio access key
    from: "[a-zA-Z0-9]{8}"
    generate: expression
    required: true
  - name: MINIO_SECRET_KEY
    description: Minio secret key
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: template.minio-secret
      labels: {}
    stringData:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
