apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: rabbitma-dc
objects:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      description: Deploys a RabbitMQ instance within a TFRS environment
    creationTimestamp: null
    generation: 3
    labels:
      template: tfrs-app-environment
    name: rabbitmq
  spec:
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: rabbitmq
    serviceName: ""
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: rabbitmq
      spec:
        containers:
        - command:
          - rabbitmq-server
          image: docker-registry.default.svc:5000/mem-tfrs-tools/rabbitmq-tfrs:dev
          imagePullPolicy: Always
          name: rabbitmq
          ports:
          - containerPort: 15672
            name: web-management
            protocol: TCP
          - containerPort: 5672
            name: amqp
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5672
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: rabbit
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
    volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        name: rabbit
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 512Mi
      status:
        phase: Pending
  status:
    collisionCount: 0
    currentReplicas: 1
    currentRevision: rabbitmq-d5f45ddf7
    observedGeneration: 3
    readyReplicas: 1
    replicas: 1
    updateRevision: rabbitmq-d5f45ddf7
    updatedReplicas: 1
