apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: RABBITMQ_USER
  description: "Username for the RabbitMQ instance"
  value: rabbitmq
- name: RABBITMQ_PASS
  description: "Password securing the RabbitMQ instance"
  from: zeva[A-Z0-9]{3}
  generate: expression
  required: true
- name: ERLANG_COOKIE
  description: "Cookie used for authentication of cluster nodes"
  from: zeva[A-Z0-9]{3}
  generate: expression
  required: true
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: ${NAME}${SUFFIX}-${CLUSTER_NAME}-secret
  stringData:
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    cookie: ${ERLANG_COOKIE}
  type: Opaque