apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: rabbitmq-bc
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: rabbitmq-tfrs
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: rabbitmq-tfrs:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      dockerfile: |-
        FROM rabbitmq:3.7.7-management
        RUN apt-get update
        RUN apt-get install -y gettext-base
        RUN chgrp -R root /var/log/rabbitmq
        RUN chmod -R g+w /var/log/rabbitmq
        ARG ADMIN_PASSWORD
        ARG TFRS_PASSWORD
        RUN echo "H4sICHQioFsCA2RlZmluaXRpb25zLnN0cmlwcGVkLmpzb24AtVLLasMwELz7K4zpqQQXWtpAb4FQ6KEP4kIPpZiNLUsCWzLSKmkx/vdKwrYgNukpF4FmdjWzs+qiOE4U7Pcc8wNRmkuRPMbJXbpO18nKkUZb2GJf9hLHnT8tLKAhrhLKhgtf6eEWtD5KVTrqarN9eX7N3zdZ9vm224YiBppxQXOoqVQcWeOqBxPjA/lYpBnc3j+EZgSqJ2GuUQFKlXi2Xy17xMpOsGzx42mXXcrhYMqe3z7JA5Maz0R5432eNLVENVy7vSx0ut3MB/Q64cEJL6SoODXKi6XXgTjaEWegIlAO2GK4o/bJB7iQ+JQH+SkYCErO5Cgk8ooXgD60f53hb+vbKhDSYMBLYxdeOwqVIRMMBmVekpp41xXUOnBcIFEC6hkBipqGCL/9rg8jRX30B3tV1p2CAwAA" | base64 -d | gunzip - | envsubst > /etc/rabbitmq/definitions.json
      type: Dockerfile
    strategy:
      dockerStrategy:
        env:
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ADMIN_PASSWORD
              name: rabbitmq
        - name: TFRS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: TFRS_PASSWORD
              name: rabbitmq
      type: Docker
    triggers: []
  status:
    lastVersion: 0
