apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: template-rabbitmq-secret
parameters:
- name: RABBITMQ_PASS
  description: "Password securing the RabbitMQ instance"
  generate: expression
  from: "[a-zA-Z0-9]{16}"
- name: ERLANG_COOKIE
  description: "Cookie used for authentication of cluster nodes"
  generate: expression
  from: "[a-zA-Z0-9]{16}"
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: template-rabbitmq-secret
      labels: {}
    stringData:
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
      ERLANG_COOKIE: "${ERLANG_COOKIE}"

