apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: test-result
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: test-result
      annotations:
        as-copy-of: zeva-template-postgresql
      labels: {}
    stringData:
      DATABASE_USER: "${ZEVA_DB_USER}"
      DATABASE_PASSWORD: "${ZEVA_DB_PASSWORD}"
parameters:
  - description: Username for PostgreSQL user that will be used for accessing the database.
    from: zeva[A-Z0-9]{3}
    generate: expression
    name: ZEVA_DB_USER
    required: true
  - description: Password for the PostgreSQL connection user.
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    name: ZEVA_DB_PASSWORD
    required: true