---
kind: Template
apiVersion: v1
labels:
  template: zeva-generic-policy
metadata:
  name: zeva-generic-policy
  creationTimestamp:
parameters:
  - name: NAMESPACE_PREFIX
    displayName: Namespace prefix
    description: either tbiwaq or e52f12
    required: true     
  - name: ENV_NAME
    displayName: Environment name
    description: values are tools, dev, test or prod
    required: true         
  - name: API_VERSION
    displayName: Api version
    description: Api version, either secops.pathfinder.gov.bc.ca/v1alpha1 or security.devops.gov.bc.ca/v1alpha1
    required: true    
objects:
# only allow frontend and backend to communicate with internet
#  - kind: NetworkSecurityPolicy
#    apiVersion: ${API_VERSION}
#    metadata:
#      name: egress-internet
#    spec:
#      description: |
#        allow the ${NAMESPACE_PREFIX}-${ENV_NAME} namespace to talk to the internet.
#      source:
#        - - $namespace=${NAMESPACE_PREFIX}-${ENV_NAME}
#      destination:
#        - - ext:network=any

# The internal communicates in namespace are defined in nsp-env.yaml
#  - kind: NetworkSecurityPolicy
#    apiVersion: ${API_VERSION}
#    metadata:
#      name: intra-namespace-comms
#    spec:
#      description: |
#        allow the ${NAMESPACE_PREFIX}-${ENV_NAME} namespace to talk to itself
#      source:
#        - - $namespace=${NAMESPACE_PREFIX}-${ENV_NAME}
#     destination:
#        - - $namespace=${NAMESPACE_PREFIX}-${ENV_NAME}
  - kind: NetworkSecurityPolicy
    apiVersion: ${API_VERSION}
    metadata:
      name: int-cluster-k8s-api-comms
    spec:
      description: |
        allow ${NAMESPACE_PREFIX}-${ENV_NAME} pods to talk to the k8s api
      destination:
        - - int:network=internal-cluster-api-endpoint
      source:
        - - $namespace=${NAMESPACE_PREFIX}-${ENV_NAME}