apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: base image for jenkins
      labels:
        shared: "true"
      creationTimestamp: null
      generation: 0
      name: bcgov-jenkins-basic
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      name: bcgov-jenkins-basic
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: "bcgov-jenkins-basic:v2-20210520"
      resources:
        limits:
          cpu: "2"
          memory: 6Gi
        requests:
          cpu: "1"
          memory: 2Gi
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 2
      strategy:
        type: Docker
        dockerStrategy:
          pullSecret:
            name: redhat-artifactory-secret
      postCommit: {}
      source:
        type: Git
        git:
          uri: "https://github.com/kuanfandevops/openshift-components.git"
          ref: kuan-version
        contextDir: cicd/jenkins-basic/docker
      triggers:
        - type: ConfigChange
      runPolicy: SerialLatestOnly
    status:
      lastVersion: 0
