apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: base image for jenkins
    labels:
      shared: "true"
    creationTimestamp: null
    generation: 0
    name: bcgov-jenkins-basic
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: bcgov-jenkins-basic
  spec:
    failedBuildsHistoryLimit: 2
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: bcgov-jenkins-basic:v2-20200303
    postCommit: {}
    resources:
      limits:
        cpu: "2"
        memory: 6Gi
      requests:
        cpu: "1"
        memory: 2Gi
    runPolicy: SerialLatestOnly
    source:
      contextDir: cicd/jenkins-basic/docker
      git:
        ref: master
        uri: https://github.com/BCDevOps/openshift-components.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: rhel7-atomic:7.7-371
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 0
