apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: base image for jenkins
      labels:
        shared: "true"
      creationTimestamp: null
      generation: 0
      name: bcgov-jenkins-basic
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      name: bcgov-jenkins-basic
    spec:
      failedBuildsHistoryLimit: 2
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: bcgov-jenkins-basic:v2-20210520
      postCommit: {}
      resources:
        limits:
          cpu: "2"
          memory: 6Gi
        requests:
          cpu: "1"
          memory: 2Gi
      runPolicy: SerialLatestOnly
      source:
        contextDir: cicd/jenkins-basic/docker
        git:
          ref: kuan-version
          uri: https://github.com/kuanfandevops/openshift-components.git
        type: Git
      strategy:
        from:
          kind: DockerImage
          name: registry.redhat.io/ubi8/ubi:8.2
        type: Docker
      successfulBuildsHistoryLimit: 5
      triggers:
        - imageChange: {}
          type: ImageChange
        - type: ConfigChange
    status:
      lastVersion: 0
