apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
parameters:
  - name: ENV_NAME
    displayName: zeva env anme
    description: zeva env name, sample values dev, test and prod
    required: true
  - name: ZEVA_RELEASE
    displayName: zeva release name
    description: zeva release name
    required: true
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the envoy image
    creationTimestamp: null
    name: envoy
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: envoy
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: envoy:${ZEVA_RELEASE}
    postCommit: {}
    resources: {}
    runPolicy: SerialLatestOnly
    source:
      git:
        ref: ${ZEVA_RELEASE}
        uri: https://github.com/bcgov/zeva.git
      type: Git
      contextDir: openshift/templates/envoy
    strategy:
      dockerStrategy:
        buildArgs:
          - name: env_name
            value: ${ENV_NAME}
        forcePull: false
        noCache: true
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers: []
  status:
    lastVersion: 0
