apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: zeva-patroni-app
parameters:
- name: APP_DB_PASSWORD
  description: "zeva user password"
  required: true
- name: APP_DB_USERNAME
  description: "zeva username"
  required: true 
- name: METABASE_PASSWORD
  description: "metabase password"
  required: true 
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: zeva-patroni-app
  stringData:
    app-db-name: zeva
    app-db-password: ${APP_DB_PASSWORD}
    app-db-username: ${APP_DB_USERNAME}
    metabaseuser-name: metabaseuser
    metabaseuser-password: ${METABASE_PASSWORD}
  type: Opaque