apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: backend
parameters:
  - name: ENV_NAME
    value: dev
    displayName: Environment name
    description: Environment name, dev, test and prod
    required: true
  - name: CPU_REQUEST
    displayName: Requested CPU
    description: Requested CPU
    required: true
  - name: CPU_LIMIT
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the backend image
    creationTimestamp: null
    name: backend
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: backend
    labels:
      name: backend
      app: zeva
      role: backend
      env: ${ENV_NAME}
  spec:
    ports:
      - name: backend
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      name: backend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    creationTimestamp: null
    labels:
      template: backend
    name: backend
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      name: backend
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        mid:
          execNewPod:
            command:
            - /bin/sh
            - -c
            - python manage.py migrate;
            containerName: backend
          failurePolicy: Abort
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: backend
        name: backend
      spec:
        containers:
          - name: backend
            image:
            imagePullPolicy: IfNotPresent
            env:
              - name: DATABASE_NAME
                value: zeva
              - name: DATABASE_USER
                valueFrom:
                  secretKeyRef:
                    name: postgresql
                    key: DATABASE_USER
              - name: DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql
                    key: DATABASE_PASSWORD
              - name: DATABASE_ENGINE
                value: postgresql
              - name: DATABASE_SERVICE_NAME
                value: postgresql
              - name: DATABASE_SERVICE_HOST
                value: postgresql.tbiwaq-${ENV_NAME}.svc.cluster.local
              - name: KEYCLOAK_CERTS_URL
                value: postgres
              - name: POSTGRESQL_SERVICE_PORT
                value: '5432'
              - name: KEYCLOAK_CERTS_URL
                valueFrom:
                  configMapKeyRef:
                    name: zeva-config
                    key: keycloak_certs_url
              - name: KEYCLOAK_REALM
                valueFrom:
                  configMapKeyRef:
                    name: zeva-config
                    key: keycloak_realm
              - name: KEYCLOAK_AUTHORITY
                valueFrom:
                  configMapKeyRef:
                    name: zeva-config
                    key: keycloak_authority
              - name: KEYCLOAK_ISSUER
                valueFrom:
                  configMapKeyRef:
                    name: zeva-config
                    key: keycloak_issuer
              - name: KEYCLOAK_AUDIENCE
                valueFrom:
                  configMapKeyRef:
                    name: zeva-config
                    key: keycloak_audience
              - name: KEYCLOAK_CLIENT_ID
                valueFrom:
                  configMapKeyRef:
                    name: zeva-config
                    key: keycloak_client_id
              - name: DJANGO_DEBUG
                valueFrom:
                  configMapKeyRef:
                    name: zeva-config
                    key: django_debug
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /health
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 3
            ports:
            - containerPort: 8080
              protocol: TCP
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /health
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 3
            resources:
              limits:
                cpu: ${CPU_LIMIT}
                memory: ${MEMORY_LIMIT}
              requests:
                cpu: ${CPU_REQUEST}
                memory: ${MEMORY_REQUEST}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - backend
        from:
          kind: ImageStreamTag
          name: backend:${ENV_NAME}
          namespace: tbiwaq-${ENV_NAME}
        lastTriggeredImage:
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
