apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: frontend-dc
parameters:
  - name: NAME
    displayName:
    description: the module name entered when run yo bcdk:pipeline, which is zeva
    required: true
  - name: SUFFIX
    displayName:
    description: sample is -pr-0
    required: true
  - name: VERSION
    displayName:
    description:  image tag name for output
    required: true
  - name: ENV_NAME
    value: dev
    displayName: Environment name
    description: Environment name, dev, test and prod
    required: true
  - name: HOST_NAME
    displayName: Host name for route
    description: Host name for route
    required: true
  - name: CPU_REQUEST
    displayName: Requested CPU
    description: Requested CPU
    required: true
  - name: CPU_LIMIT
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
  - name: REPLICAS
    value: '1'
    required: true
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: Keeps track of changes in the client / front end image
      labels:
        shared: "true"
      creationTimestamp: null
      name: ${NAME}-frontend
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      name: ${NAME}-frontend${SUFFIX}
      labels:
        name: frontend
        app: zeva
        role: frontend
        env: ${ENV_NAME}
    spec:
      ports:
        - name: web
          port: 3000
          protocol: TCP
          targetPort: 3000
        - name: websocket-notifications
          port: 5002
          protocol: TCP
          targetPort: 5002
      selector:
        name: ${NAME}-frontend${SUFFIX}
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      creationTimestamp: null
      annotations:
        haproxy.router.openshift.io/balance: source
        haproxy.router.openshift.io/timeout: 1200s            
      labels:
        name: frontend
        app: zeva
        role: frontend
        env: ${ENV_NAME}
      name: ${NAME}-sockjs-node${SUFFIX}
    spec:
      host: ${HOST_NAME}
      path: /sockjs-node
      port:
        targetPort: web
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}-frontend${SUFFIX}
        weight: 100
      wildcardPolicy: None
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      creationTimestamp: null
      labels:
        name: frontend
        app: zeva
        role: frontend
        env: ${ENV_NAME}
      name: ${NAME}-frontend${SUFFIX}
    spec:
      host: ${HOST_NAME}
      port:
        targetPort: web
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}-frontend${SUFFIX}
        weight: 100
      wildcardPolicy: None
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}-frontend${SUFFIX}
      labels:
        app: zeva
        role: frontend
        env: ${ENV_NAME}
      annotations:
        description: Defines how to deploy the frontend application
      creationTimestamp: null
    spec:
      replicas: ${{REPLICAS}}
      revisionHistoryLimit: 10
      selector:
        name: ${NAME}-frontend${SUFFIX}
      strategy:
        activeDeadlineSeconds: 21600
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        type: Recreate
      template:
        metadata:
          creationTimestamp: null
          labels:
            name: ${NAME}-frontend${SUFFIX}
        spec:
          containers:
            - env:
                - name: KEYCLOAK_CERTS_URL
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_certs_url
                - name: KEYCLOAK_REALM
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_realm
                - name: KEYCLOAK_AUTHORITY
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_authority
                - name: KEYCLOAK_ISSUER
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_issuer
                - name: KEYCLOAK_URL
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_url
                - name: KEYCLOAK_AUDIENCE
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_audience
                - name: KEYCLOAK_CLIENT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_client_id
                - name: KEYCLOAK_REALM_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_realm_name
                - name: RABBITMQ_ENABLED
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: rabbitmq_enabled
                - name: APIBASE
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: apibase
                - name: KEYCLOAK_LOGOUT_REDIRECT_URL
                  valueFrom:
                    configMapKeyRef:
                      name: ${NAME}-config${SUFFIX}
                      key: keycloak_logout_redirect_url
              image:
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 10
                initialDelaySeconds: 50
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 3000
                timeoutSeconds: 3
              name: frontend
              ports:
                - containerPort: 3000
                  protocol: TCP
                - containerPort: 5002
                  protocol: TCP
              readinessProbe:
                failureThreshold: 10
                initialDelaySeconds: 40
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 3000
                timeoutSeconds: 3
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /opt/app-root/src/src/app/config
                  name: ${NAME}-frontend-config${SUFFIX}              
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - configMap:
                defaultMode: 444
                name: ${NAME}-frontend-config${SUFFIX}
              name: ${NAME}-frontend-config${SUFFIX}
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - frontend
            from:
              kind: ImageStreamTag
              name: ${NAME}-frontend:${VERSION}
            lastTriggeredImage:
          type: ImageChange
        - type: ConfigChange
    status:
      availableReplicas: 0
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      unavailableReplicas: 0
      updatedReplicas: 0
