apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: maintenance-page
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: maintenance-page
    name: maintenance-page
  spec:
    ports:
    - name: 2015-tcp
      port: 2015
      protocol: TCP
      targetPort: 2015
    selector:
      app: maintenance-page
      deploymentconfig: maintenance-page
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 47
    labels:
      app: maintenance-page
    name: maintenance-page
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: maintenance-page
      deploymentconfig: maintenance-page
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: maintenance-page
          deploymentconfig: maintenance-page
      spec:
        containers:
        - image: 
          imagePullPolicy: Always
          name: maintenance-page
          ports:
          - containerPort: 2015
            protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - maintenance-page
        from:
          kind: ImageStreamTag
          name: maintenance-page:latest
          namespace: tbiwaq-tools
        lastTriggeredImage: 
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
