replicaCount: 1

envName: dev
suffix: -dev-1513

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  cpuAverageUtilization: 80

healthCheckDelay:  30

resources:
  limits:
    cpu: 160m
    memory: 400Mi
  requests:
    cpu: 80m
    memory: 200Mi
    
backendRoute: 
  create: true
  hostName: zeva-backend-dev-1513.apps.silver.devops.gov.bc.ca