apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: zeva-configs
parameters:
  - name: NAME
    displayName: null
    description: 'the module name entered when run yo bcdk:pipeline, which is zeva'
    required: true
  - name: SUFFIX
    displayName: null
    description: sample is -dev-97
    required: true
  - name: VERSION
    displayName: null
    description: image tag name for output
    required: true
  - name: ENV_NAME
    value: dev
    displayName: Environment name
    description: 'Environment name, dev, test and prod'
    required: true
  - name: SSO_NAME
    value: sso-dev
    displayName: SSO Name
    description: values include sso-dev, sso-test and sso
    required: true
  - name: KEYCLOAK_REALM
    value: rzh2zkjq
    displayName: keycload realm name
    description: keycload realm name, value is rzh2zkjq
    required: true
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      creationTimestamp: null
      name: ${NAME}-config${SUFFIX}
    data:
      apibase: https://${NAME}-backend${SUFFIX}.tbiwaq-${ENV_NAME}.svc.cluster.local:8080/api/
      database_engine: postgresql
      database_name: zeva
      database_service_name: ${NAME}-postgresql${SUFFIX}
      django_debug: 'False'
      email_from_address: donotreply@gov.bc.ca
      email_sending_enabled: 'False'
      keycloak_audience: zeva
      keycloak_authority: https://${SSO_NAME}.pathfinder.gov.bc.ca/auth/realms/${KEYCLOAK_REALM}
      keycloak_certs_url: https://${SSO_NAME}.pathfinder.gov.bc.ca/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
      keycloak_client_id: zeva
      keycloak_issuer: https://${SSO_NAME}.pathfinder.gov.bc.ca/auth/realms/${KEYCLOAK_REALM}
      keycloak_realm_name: ${KEYCLOAK_REALM}
      keycloak_realm_url: https://${SSO_NAME}.pathfinder.gov.bc.ca/auth/realms/${KEYCLOAK_REALM}
      keycloak_realm: https://${SSO_NAME}.pathfinder.gov.bc.ca/auth/realms/${KEYCLOAK_REALM}
      keycloak_sa_baseurl: https://${SSO_NAME}.pathfinder.gov.bc.ca
      keycloak_sa_client_id: zeva-django-sa
      keycloak_sa_realm: ${KEYCLOAK_REALM}
      keycloak_url: https://${SSO_NAME}.pathfinder.gov.bc.ca/auth
      postgresql_service_host: ${NAME}-postgresql${SUFFIX}.tbiwaq-${ENV_NAME}.svc.cluster.local
      postgresql_service_port: '5432'
      rabbitmq_enabled: 'False'
      rabbitmq_host: rabbitmq.tbiwaq-${ENV_NAME}.svc.cluster.local
      rabbitmq_port: '5672'
      rabbitmq_user: zeva
      rabbitmq_vhost: /zeva
      smtp_server_host: apps.smtp.gov.bc.ca
      smtp_server_port: '25'
