apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: zeva-keycloak-secret
parameters:
  - name: KEYCLOAK_SA_CLIENT_SECRET
    description: KEYCLOAK_SA_CLIENT_SECRET
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: zeva-keycloak
      labels: {}
    stringData:
      KEYCLOAK_SA_CLIENT_SECRET: "${KEYCLOAK_SA_CLIENT_SECRET}"

