apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: zeva-rabbitmq-secret
parameters:
  - name: ADMIN_PASSWORD
    description: rabbitmq admin user
    required: true
  - name: ZEVA_PASSWORD
    description: rabbitmq zeva password
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: zeva-rabbitmq
      labels: {}
    stringData:
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      ZEVA_PASSWORD: "${ZEVA_PASSWORD}"

