apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: zeva-rabbitmq-secret
parameters:
  - name: ENV_NAME
    required: true
  - name: ADMIN_PASSWORD
    description: rabbitmq admin user
    from: "[a-zA-Z0-9]{8}"
    generate: expression
    required: true
  - name: ZEVA_PASSWORD
    description: rabbitmq zeva password
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: zeva-rabbitmq-${ENV_NAME}
      labels: {}
    stringData:
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      ZEVA_PASSWORD: "${ZEVA_PASSWORD}"

