apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: zeva-secrets
parameters:
  - name: DATABASE_USER
    description: Username for PostgreSQL
    from: zeva[A-Z0-9]{3}
    generate: expression
    required: true
  - name: DATABASE_PASSWORD
    description: Password for the PostgreSQL connection
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    required: true
  - name: DATABASE_USER_UNITTEST
    description: Username for PostgreSQL unit test database
    from: zevaunittest[A-Z0-9]{3}
    generate: expression
    required: true
  - name: DATABASE_PASSWORD_UNITTEST
    description: Password for the PostgreSQL unit test database user.
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    required: true
  - name: MINIO_ACCESS_KEY
    description: Minio access key
    from: "[a-zA-Z0-9]{8}"
    generate: expression
    required: true
  - name: MINIO_SECRET_KEY
    description: Minio secret key
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    required: true
  - name: DJANGO_SECRET_KEY
    description: django secret key
    from: "[a-zA-Z0-9]{50}"
    generate: expression
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: zeva-postgresql
      labels: {}
    stringData:
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
  - apiVersion: v1
    kind: Secret
    metadata:
      name: zeva-postgresql-unittest
      labels: {}
    stringData:
      DATABASE_USER: "${DATABASE_USER_UNITTEST}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD_UNITTEST}"
  - apiVersion: v1
    kind: Secret
    metadata:
      name: zeva-minio
      labels: {}
    stringData:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
  - apiVersion: v1
    kind: Secret
    metadata:
      name: zeva-django-secret-key
      labels: {}
    stringData:
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
