apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: backend-autoscaler
parameters:
  - name: NAME
    displayName:
    description: the module name entered when run yo bcdk:pipeline, which is zeva
    required: true
  - name: SUFFIX
    displayName:
    description: 
    required: true
  - name: MIN_REPLICAS
    displayName:
    description: 
    required: true
  - name: MAX_REPLICAS
    displayName:
    description: 
    required: true            
objects:
  - apiVersion: autoscaling/v1
    kind: HorizontalPodAutoscaler
    metadata:
      name: ${NAME}-backend${SUFFIX}-autoscaler
    spec:
      scaleTargetRef:
        apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig 
        name: ${NAME}-backend${SUFFIX} 
        subresource: scale
      minReplicas: ${{MIN_REPLICAS}} 
      maxReplicas: ${{MAX_REPLICAS}} 
      targetCPUUtilizationPercentage: 80 