apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: frontend-dc
parameters:
  - name: ENV_NAME
    value: dev
    displayName: Environment name
    description: Environment name, dev, test and prod
    required: true
  - name: CPU_REQUEST
    displayName: Requested CPU
    description: Requested CPU
    required: true
  - name: CPU_LIMIT
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      name: frontend
      labels:
        name: frontend
        app: zeva
        role: frontend
        env: ${ENV_NAME}
    spec:
      ports:
        - name: web
          port: 5001
          protocol: TCP
          targetPort: 5001
        - name: websocket-notifications
          port: 5002
          protocol: TCP
          targetPort: 5002
      selector:
        name: frontend
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      creationTimestamp: null
      labels:
        name: frontend
        app: zeva
        role: frontend
        env: ${ENV_NAME}
      name: ${ENV_NAME}-zeroemissionvehicles-frontend
    spec:
      host: ${ENV_NAME}-zeroemissionvehicles.pathfinder.gov.bc.ca
      port:
        targetPort: http-in
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: envoy
        weight: 100
      wildcardPolicy: None
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: frontend
      labels:
        name: frontend
        app: zeva
        role: frontend
        env: ${ENV_NAME}
      annotations:
        description: Defines how to deploy the frontend application
      creationTimestamp: null
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        name: frontend
      strategy:
        activeDeadlineSeconds: 21600
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        type: Recreate
      template:
        metadata:
          creationTimestamp: null
          labels:
            name: frontend
          name: frontend
        spec:
          containers:
            - name: frontend
              image:
              env:
                - name: KEYCLOAK_CERTS_URL
                  valueFrom:
                    configMapKeyRef:
                      name: zeva-config
                      key: keycloak_certs_url
                - name: KEYCLOAK_REALM
                  valueFrom:
                    configMapKeyRef:
                      name: zeva-config
                      key: keycloak_realm
                - name: KEYCLOAK_AUTHORITY
                  valueFrom:
                    configMapKeyRef:
                      name: zeva-config
                      key: keycloak_authority
                - name: KEYCLOAK_ISSUER
                  valueFrom:
                    configMapKeyRef:
                      name: zeva-config
                      key: keycloak_issuer
                - name: KEYCLOAK_URL
                  valueFrom:
                    configMapKeyRef:
                      name: zeva-config
                      key: keycloak_url
                - name: KEYCLOAK_AUDIENCE
                  valueFrom:
                    configMapKeyRef:
                      name: zeva-config
                      key: keycloak_audience
                - name: KEYCLOAK_CLIENT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: zeva-config
                      key: keycloak_client_id
                - name: KEYCLOAK_REALM_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: zeva-config
                      key: keycloak_realm_name
                - name: RABBITMQ_ENABLED
                  valueFrom:
                    configMapKeyRef:
                      name: zeva-config
                      key: rabbitmq_enabled
                - name: APIBASE
                  valueFrom:
                    configMapKeyRef:
                      name: zeva-config
                      key: apibase
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 40
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 5001
                timeoutSeconds: 3
              ports:
                - containerPort: 5001
                  protocol: TCP
                - containerPort: 5002
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 5001
                timeoutSeconds: 3
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - frontend
            from:
              kind: ImageStreamTag
              name: frontend:${ENV_NAME}
              namespace: tbiwaq-${ENV_NAME}
            lastTriggeredImage:
          type: ImageChange
        - type: ConfigChange
    status:
      availableReplicas: 0
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      unavailableReplicas: 0
      updatedReplicas: 0
