apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: frontend
parameters:
  - name: NAME
    displayName:
    description: the module name entered when run yo bcdk:pipeline, which is zeva
    required: true
  - name: SUFFIX
    displayName:
    description: sample is -pr-0
    required: true
  - name: VERSION
    displayName:
    description:  image tag name for output
    required: true
  - name: GIT_URL
    displayName:
    description: zeva repo
    required: true
  - name: GIT_REF
    displayName:
    description: zeva branch name of the pr
    required: true
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the client / front end image
    labels:
      shared: "true"
    creationTimestamp: null
    generation: 643
    name: ${NAME}-frontend
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application  
    labels:
      buildname: "frontendbc"
      shared: "true"
    creationTimestamp: null
    name: ${NAME}-frontend${SUFFIX}
  spec:
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-frontend:${VERSION}
    resources:
      limits:
        cpu: 2000m
        memory: 2G
      requests:
        cpu: 500m
        memory: 200M
    runPolicy: Serial
    source:
      git:
        ref: ${GIT_REF}
        uri: ${GIT_URL}
      type: Git
      contextDir: frontend
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:14-1-28
          namespace: e52f12-tools
        pullSecret:
          name: zeva-image-pull-secret
        forcePull: true
        noCache: true          
        env:
          - name: ARTIFACTORY_USER
            valueFrom:
              secretKeyRef:
                name: artifacts-zeva-artifactory-service-account-xgchey
                key: username
          - name: ARTIFACTORY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: artifacts-zeva-artifactory-service-account-xgchey
                key: password
      type: Source
    successfulBuildsHistoryLimit: 5
  status:
    lastVersion: 0