apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: jenkins-restart-bc
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: Keeps track of changes in the image
      creationTimestamp: null
      name: jenkins-restart
    spec:
      lookupPolicy:
        local: false
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      name: jenkins-restart
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: jenkins-restart:latest
          namespace: e52f12-tools
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        contextDir: openshift/templates/cronjobs/jenkins-restart
        git:
          ref: release-1.26.0
          uri: https://github.com/bcgov/zeva.git
        type: Git
      strategy:
        type: Docker
        dockerStrategy:
          pullSecret:
            name: docker-artifactory-secret
      successfulBuildsHistoryLimit: 5
      triggers: []
    status:
      lastVersion: 0
