apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: zeva-keycloak-secret
parameters:
  - name: KEYCLOAK_SA_CLIENT_SECRET
    description: teh secret for private client
    required: true
  - name: clientId
    description:
    required: true
  - name: clientSecret
    description:
    required: true
  - name: zevaPublic
    description: the key in the pubic client url, is not the client id
    required: true
  - name: realmId
    description:
    required: true
  - name: host
    description: host is sso host name, such as sso-dev.[ocp name].gov.bc.ca,sso-test.[ocp name].gov.bc.ca and sso.[ocp name].gov.bc.ca
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: zeva-keycloak
      labels: {}
    stringData:
      KEYCLOAK_SA_CLIENT_SECRET: "${KEYCLOAK_SA_CLIENT_SECRET}"
      clientId: "${clientId}"
      clientSecret: "${clientSecret}"
      zevaPublic: "${zevaPublic}"
      realmId: "${realmId}"
      host: "${host}"
