apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "zeva-backend.name" . }}-autoscaler{{ .Values.suffix }}
spec:
  scaleTargetRef:
    kind: DeploymentConfig
    name: {{ template "zeva-backend.name" . }}{{ .Values.suffix }}
    apiVersion: apps.openshift.io/v1
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.cpuAverageUtilization }}
