{{- if .Values.backendRoute.create }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: 
  annotations:      
    haproxy.router.openshift.io/timeout: 1500s      
  name: {{ template "zeva-backend.name" . }}{{ .Values.suffix }}
  labels: {{ include "zeva-backend.labels" . | nindent 8 }}
spec:
  host: {{ .Values.backendRoute.hostName }}
  path: /api
  port:
    targetPort: backend
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ template "zeva-backend.name" . }}{{ .Values.suffix }}
    weight: 100
  wildcardPolicy: None
{{- end }}