apiVersion: v1
kind: Service
metadata:
  name: {{ template "zeva-backend.fullname" . }}
  labels: {{- include "zeva-backend.labels" . | nindent 4 }}
spec:
  ports:
    - name: backend
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "zeva-backend.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP

