## For each release, the value of workflow name, branches, PR_NUMBER and RELEASE_NAME need to be adjusted accordingly
## Also change the .pipelin/lib/config.js version number
name: new-python-image

on:
  push:
    branches: [ new-python39-image-1.42.0 ]
  workflow_dispatch:
  workflow_call:

env:
  ## The pull request number of the Tracking pull request to merge the release branch to main
  PR_NUMBER: 1102
  RELEASE_NAME: new-python39-image-1.42.0

jobs:

  ## This is the CI job
  build:

    name: Build ZEVA on Openshift
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:

      ## it will checkout to /home/runner/work/zeva/zeva
      - name: Check out repository
        uses: actions/checkout@v2

      # open it when zeva updated the python packages
      - name: Run django tests 
        uses: kuanfandevops/django-test-action@zeva-django-test
        with:
          settings-dir-path: "backend/zeva"
          requirements-file: "backend/requirements.txt"
          managepy-dir: backend
