name: Create Release after merging to master
on:
  pull_request:
    types: [closed]
    branches:
      - 'master'     

jobs:
  replace-release-name:

           
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Replace release name
        uses: mad9000/actions-find-and-replace-string@4
        with:
          source: ${{ github.event.pull_request.head.ref }}
          find: 'release-'
          replace: 'v'
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.pull_request.head.ref }}
          tag_name: ${{ github.event.pull_request.head.ref }}
          body: |
            ${{ github.event.pull_request.body }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
