## For each release, please update the value of workflow name, branches, PR_NUMBER and RELEASE_NAME
## Also update frontend/package.json version

name: Frontend Unit Test 1.46.0

on:
  push:
    branches: [ release-1.46.0 ]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:

  frontend-unit-test:

    name: Run Frontend Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Fronend Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.2.1
        continue-on-error: false
        with:
          working-directory: frontend
          test-script: npm run test
        

