name: pipeline-test

on:
  push:
    branches:
      - pipeline-test-1.63.0
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}
  

jobs:
  get-default-branch:
    runs-on: ubuntu-latest
    steps:

      - name: Get Current Default Branch and Set Tag Name
        id: get_default_branch
        run: |
          # Fetch the current default branch using the GitHub API
          current_default_branch=$(gh api repos/${{ github.repository }} | jq -r '.default_branch')
          echo "Current default branch is: $current_default_branch"
          echo "current_default_branch=$current_default_branch" >> $GITHUB_OUTPUT
          
          # # Extract the current release version number (assumes format is release-X.Y.Z)
          # current_version=$(echo "$current_default_branch" | grep -oP '\d+\.\d+\.\d+')
          # echo "Current version extracted: $current_version"

          # # Create tag in the format vX.Y.Z
          # tag_name="v$current_version"
          # echo "Generated tag name: $tag_name"

      - name: Get New Release Branch
        id: get_new_release_branch
        run: |
          # Get the current default branch from the previous step
          current_default_branch="${{ steps.get_default_branch.outputs.current_default_branch }}"
          
          # Extract the current release version number (assumes format is release-X.Y.Z)
          current_version=$(echo "$current_default_branch" | grep -oP '\d+\.\d+\.\d+')
          
          # Increment the minor version (X.Y.Z -> X.(Y+1).0)
          major_version=$(echo "$current_version" | cut -d. -f1)
          minor_version=$(echo "$current_version" | cut -d. -f2)
          patch_version=$(echo "$current_version" | cut -d. -f3)

          # Increment the minor version by 1 for the new release branch
          new_minor_version=$((minor_version + 1))
          new_release_branch="release-${major_version}.${new_minor_version}.0"
          
          echo "New release branch will be: $new_release_branch"
          echo "new_release_branch=$new_release_branch" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Create New Release Branch
        id: create_new_release_branch
        run: |
          # Get the new release branch name from the previous step
          new_release_branch="${{ steps.get_new_release_branch.outputs.new_release_branch }}""
          
          # Create the new branch from master
          git checkout -b $new_release_branch master
          # git push origin $new_release_branch
