name: pipeline-test

on:
  push:
    branches:
      - pipeline-test-1.63.0
  workflow_dispatch:

jobs:
  get-default-branch:
    runs-on: ubuntu-latest
    steps:

      # Step 2a: Get the current default branch and set tag name
      - name: Get Current Default Branch and Set Tag Name
        id: get_default_branch
        run: |
          # Fetch the current default branch using the GitHub API
          current_default_branch=$(gh api repos/${{ github.repository }} | jq -r '.default_branch')
          echo "Current default branch is: $current_default_branch"
          
          # Extract the current release version number (assumes format is release-X.Y.Z)
          current_version=$(echo "$current_default_branch" | grep -oP '\d+\.\d+\.\d+')
          echo "Current version extracted: $current_version"

          # Create tag in the format vX.Y.Z
          tag_name="v$current_version"
          echo "Generated tag name: $tag_name"
          
          # Set both outputs: current default branch and the tag name
          echo "::set-output name=current_default_branch::$current_default_branch"
          echo "::set-output name=tag_name::$tag_name"
