name: Label PR

on:
  pull_request:
    types: labeled
    branches:
          - 'release-*'

jobs:

  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: squash
          LOG: DEBUG


