## For each release, the value of workflow name, branches and VERSION need to be adjusted accordingly

name: Zeva new-pipeline Prod CI

on:
  workflow_dispatch:

env:
  GIT_URL: https://github.com/bcgov/zeva.git
  TEST_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-test
  PROD_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-build-suffix:
    name: Find Test deployment build suffix 
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.get-build-suffix.outputs.BUILD_SUFFIX }}

    steps:
      - name: Log in to Openshift
        uses: redhat-actions/oc-login@v1.3
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.TEST_NAMESPACE }}

      - id: get-build-suffix
        run: |
          build_suffix=$(oc -n ${{ env.TEST_NAMESPACE }} describe deployment/zeva-test-frontend | grep Image | awk -F ':' '{print $NF}')
          echo "Validating $build_suffix"
          if [[ "$build_suffix" =~ ^[0-9]+\.[0-9]+\.[0-9]+-[0-9]{14}$ ]]; then
            echo "Build suffix $build_suffix format is valid."
            echo "BUILD_SUFFIX=$build_suffix" >> $GITHUB_OUTPUT
          else
            echo "Error: Build suffix $build_suffix format is invalid!"
            exit 1
          fi

  deploy-on-prod:
    name: Deploy ZEVA on Prod
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [get-build-suffix]

    env:
      BUILD_SUFFIX: ${{ needs.get-build-suffix.outputs.output1 }}

    steps:
      - name: Ask for approval for ZEVA ${{ env.BUILD_SUFFIX }} Prod deployment
        uses: trstringer/manual-approval@v1.6.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: emi-hi,tim738745,kuanfandevops,JulianForeman,rogerlcleung
          minimum-approvals: 2
          issue-title: "ZEVA ${{ env.BUILD_SUFFIX }} Prod Deployment"

      - name: Checkout Manifest repository
        uses: actions/checkout@v4.1.1
        with:
          repository: bcgov-c/tenant-gitops-e52f12
          ref: main
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}

      - name: Log in to Openshift
        uses: redhat-actions/oc-login@v1.3
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.PROD_NAMESPACE }}

      - name: Tag ZEVA images to Test
        run: |
          helm -n ${{ env.PROD_NAMESPACE }} list
          oc tag ${{ env.TEST_NAMESPACE }}/zeva-backend:${{ env.BUILD_SUFFIX }} ${{ env.PROD_NAMESPACE }}/zeva-backend:${{ env.BUILD_SUFFIX }}
          oc tag ${{ env.TEST_NAMESPACE }}/zeva-frontend:${{ env.BUILD_SUFFIX }} ${{ env.PROD_NAMESPACE }}/zeva-frontend:${{ env.BUILD_SUFFIX }}

      - name: Update frontend and backend image tags
        uses: mikefarah/yq@v4.40.5
        with:
          cmd: |
            yq -i '.frontend.image.tag = "${{ env.BUILD_SUFFIX }}"' zeva/values-prod.yaml
            yq -i '.backend.image.tag = "${{ env.BUILD_SUFFIX }}"' zeva/values-prod.yaml

      - name: GitHub Commit & Push
        shell: bash {0}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add zeva/values-prod.yaml
          git commit -m "Update the image tag to ${{ env.BUILD_SUFFIX }} on Zeva Prod Environment"
          git push

