## For each release, please update the value of workflow name, branches, PR_NUMBER and RELEASE_NAME
## Also update frontend/package.json version

name: Unit Test 1.46.0

on:
  push:
    branches: [ unittest-pipeline-1.46.0 ]
  workflow_dispatch:
  workflow_call:

env:
  ## The pull request number of the Tracking pull request to merge the release branch to main
  PR_NUMBER: 1248
  RELEASE_NAME: unittest-pipeline-1.46.0
  VERSION: 1.46.0
  GIT_URL: https://github.com/bcgov/zeva.git 
  TOOLS_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
  DEV_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-dev
  TEST_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-test
  PROD_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-prod


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:

  unit-test:

    name: Run Backend Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run coverage report for django tests 
        uses: kuanfandevops/django-test-action@itvr-django-test
        continue-on-error: true
        with:
          settings-dir-path: "backend/api"
          requirements-file: "backend/requirements.txt"
          managepy-dir: backend