---
kind: Template
apiVersion: v1
labels:
  template: zeva-nsp
metadata:
  name: zeva-nsp
  creationTimestamp:
parameters:
  - name: NAMESPACE_PREFIX
    displayName: Namespace prefix
    description: either tbiwaq or e52f12
    required: true     
  - name: ENV_NAME
    displayName: Environment name
    description: values are tools, dev, test or prod
    required: true         
  - name: API_VERSION
    displayName: Api version
    description: Api version, either secops.pathfinder.gov.bc.ca/v1alpha1 or security.devops.gov.bc.ca/v1alpha1
    required: true    
objects:
  - kind: NetworkSecurityPolicy
    apiVersion: ${API_VERSION}
    metadata:
      name: pods-to-external-network
      labels:
        name: pods-to-external-network
        env: ${NAMESPACE_PREFIX}-${ENV_NAME}
    spec:
      description: |
        Allow the builds to access the internet.
        This only needs to be specified once for tools project as build only runs in tools project.
      source:
        - - $namespace=${NAMESPACE_PREFIX}-${ENV_NAME}
      destination:
        - - ext:network=any
