---
kind: Template
apiVersion: v1
labels:
  template: zeva-nsp
metadata:
  name: zeva-nsp
  creationTimestamp:
parameters:
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment Name
    required: true
objects:
  - kind: NetworkSecurityPolicy
    apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
    metadata:
      name: custom-pods-to-ocp-api
    spec:
      description: |
        pods <---> OCP
        Allow pods to talk to the internal OCP api so deployments work.
        This only needs to be specified once per environment.
        Without this policy, pods could have PU Update error when starting container
      source:
      - - $namespace=tbiwaq-${ENV_NAME}
      destination:
      - - int:network=internal-cluster-api-endpoint

  - kind: NetworkSecurityPolicy
    apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
    metadata:
      name: custom-internet-to-frontend
    spec:
      description: |
        internet <---> frontend, frontend <---> keycloak
        Allow frontend to accept requests from internet.
        This also covers frontend to keycloak
      source:
        - - ext:network=any
      destination:
        - - app=zeva
          - role=frontend
          - env=${ENV_NAME}

  - kind: NetworkSecurityPolicy
    apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
    metadata:
      name: custom-internet-to-python-backend
    spec:
      description: |
        internet <---> python backend, python backend <---> keycloak
        Allow backend to accept requests from internet.
        This also covers backend to keycloak
      source:
        - - app=zeva
          - role=python-backend
          - env=${ENV_NAME}
      destination:
        - - ext:network=any

  - kind: NetworkSecurityPolicy
    apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
    metadata:
      name: custom-frontend-to-envoy
    spec:
      description: |
        frontend <---> envoy
        Allow frontend to accept requests from internet.
      source:
        - - app=zeva
          - role=frontend
          - env=${ENV_NAME}
      destination:
        - - app=zeva
          - role=envoy
          - env=${ENV_NAME}

  - kind: NetworkSecurityPolicy
    apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
    metadata:
      name: custom-envy-to-frontend
    spec:
      description: |
        Frontend <---> Envoy
        Allow envoy to talk with frontend.
      source:
        - - app=zeva
          - role=frontend
          - env=${ENV_NAME}
      destination:
        - - app=zeva
          - role=envoy
          - env=${ENV_NAME}

  - kind: NetworkSecurityPolicy
    apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
    metadata:
      name: custom-envy-to-python-backend
    spec:
      description: |
        envoy <---> python backend
        Allow envoy to talk with python backend.
      source:
        - - app=zeva
          - role=envoy
          - env=${ENV_NAME}
      destination:
        - - app=zeva
          - role=python-backend
          - env=${ENV_NAME}

  - kind: NetworkSecurityPolicy
    apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
    metadata:
      name: custom-python-backend-to-postgresql
    spec:
      description: |
        python backend <---> postgresql
        Allow python-backend to talk with postgresql database
      source:
        - - app=zeva
          - role=python-backend
          - env=${ENV_NAME}
      destination:
        - - app=zeva
          - role=postgresql
          - env=${ENV_NAME}
