---
kind: Template
apiVersion: v1
labels:
  template: zeva-nsp
metadata:
  name: zeva-nsp
  creationTimestamp:
parameters:  
  - name: NAME
    displayName: App Name
    description: App Name
    value: 'zeva'
    required: true
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment Name
    required: true
  - name: SUFFIX
    displayName:
    description: sample is -dev-365, -test and -prod
    value: ""
    required: true    
  - name: API_VERSION
    displayName: Api version
    description: Api version, either secops.pathfinder.gov.bc.ca/v1alpha1 or security.devops.gov.bc.ca/v1alpha1
    required: true
objects:
#  - kind: NetworkSecurityPolicy
#    apiVersion: ${API_VERSION}
#    metadata:
#      name: custom-interweb-to-frontend
#    spec:
#      description: |
#        Allow frontend to communicate with internet.
#      source:
#        - - ext:network=any
#      destination:
#        - - app=zeva
#          - role=frontend
#          - env=${ENV_NAME}
  - kind: NetworkSecurityPolicy
    apiVersion: ${API_VERSION}
    metadata:
      name: custom-frontend-to-backend
    spec:
      description: |
        Allow frontend to communicate with backend.
      source:
        - - app=${NAME}${SUFFIX}
          - role=frontend
          - env=${ENV_NAME}
      destination:
        - - app=${NAME}${SUFFIX}
          - role=backend
          - env=${ENV_NAME}
  - kind: NetworkSecurityPolicy
    apiVersion: ${API_VERSION}
    metadata:
      name: custom-backend-to-patroni
    spec:
      description: |
        Allow backend to communicate with patroni.
      source:
        - - app=${NAME}${SUFFIX}
          - role=backend
          - env=${ENV_NAME}
      destination:
        - - app=${NAME}${SUFFIX}
          - role=patroni
          - env=${ENV_NAME}        
  - kind: NetworkSecurityPolicy
    apiVersion: ${API_VERSION}
    metadata:
      name: custom-patroni-to-patroni-itself
    spec:
      description: |
        Allow patroni pods to communicate in patroni cluster.
      source:
        - - cluster-name=patroni${SUFFIX}
      destination:
        - - cluster-name=patroni${SUFFIX}
  - kind: NetworkSecurityPolicy
    apiVersion: ${API_VERSION}
    metadata:
      name: custom-backendmidlifecyclepod-to-patroni
    spec:
      description: |
        Allow backend to communicate with patroni.
      source:
        - - openshift.io/deployer-pod.type=hook-mid
      destination:
        - - cluster-name=patroni${SUFFIX}      
#  - kind: NetworkSecurityPolicy
#    apiVersion: ${API_VERSION}
#    metadata:
#      name: custom-pods-to-ocp-api
#    spec:
#      description: |
#        Allow pods to talk to the internal OCP api so deployments work.
#        This only needs to be specified once per environment.
#        Without this policy, pods could have PU Update error when starting container
#      source:
#        - - $namespace=e52f12-${ENV_NAME}
#      destination:
#        - - int:network=internal-cluster-api-endpoint
  - kind: NetworkSecurityPolicy
    apiVersion: ${API_VERSION}
    metadata:
      name: custom-backend-to-keycloak
    spec:
      description: |
        Allow backend pod to communicate with keycloak
      source:
        - - app=${NAME}${SUFFIX}
          - role=backend
          - env=${ENV_NAME}
      destination:
        - - $namespace=devops-sso-${ENV_NAME}
          - app=sso-${ENV_NAME}
