---
kind: Template
apiVersion: v1
labels:
  template: zeva-nsp
metadata:
  name: zeva-nsp
  creationTimestamp:
parameters:  
  - name: NAME
    displayName: App Name
    description: App Name
    value: 'zeva'
    required: true
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment Name
    required: true
  - name: SUFFIX
    displayName:
    description: sample is -dev-365, -test and -prod
    value: ""
    required: true    
  - name: API_VERSION
    displayName: Api version
    description: Api version, either secops.pathfinder.gov.bc.ca/v1alpha1 or security.devops.gov.bc.ca/v1alpha1
    required: true
objects:
  - kind: NetworkSecurityPolicy
    apiVersion: ${API_VERSION}
    metadata:
      name: ${NAME}${SUFFIX}-custom-frontend-to-backend
    spec:
      description: |
        Allow frontend to communicate with backend.
      source:
        - - app=${NAME}${SUFFIX}
          - role=frontend
          - env=${ENV_NAME}
      destination:
        - - app=${NAME}${SUFFIX}
          - role=backend
          - env=${ENV_NAME}
  - kind: NetworkSecurityPolicy
    apiVersion: ${API_VERSION}
    metadata:
      name: ${NAME}${SUFFIX}-custom-backend-to-patroni
    spec:
      description: |
        Allow backend to communicate with patroni.
      source:
        - - app=${NAME}${SUFFIX}
          - role=backend
          - env=${ENV_NAME}
      destination:
        - - app=${NAME}${SUFFIX}
          - role=patroni
          - env=${ENV_NAME}        
  - kind: NetworkSecurityPolicy
    apiVersion: ${API_VERSION}
    metadata:
      name: ${NAME}${SUFFIX}-custom-patroni-to-patroni-itself
    spec:
      description: |
        Allow patroni pods to communicate in patroni cluster.
      source:
        - - cluster-name=patroni${SUFFIX}
      destination:
        - - cluster-name=patroni${SUFFIX}
  - kind: NetworkSecurityPolicy
    apiVersion: ${API_VERSION}
    metadata:
      name: ${NAME}${SUFFIX}-custom-backendmidlifecyclepod-to-patroni
    spec:
      description: |
        Allow backend mid lifecycle pod to run django migrations against patroni.
      source:
        - - openshift.io/deployer-pod.type=hook-mid
      destination:
        - - cluster-name=patroni${SUFFIX}      
  - kind: NetworkSecurityPolicy
    apiVersion: ${API_VERSION}
    metadata:
      name: ${NAME}${SUFFIX}-custom-backend-to-keycloak
    spec:
      description: |
        Allow backend pod to communicate with keycloak
      source:
        - - app=${NAME}${SUFFIX}
          - role=backend
          - env=${ENV_NAME}
      destination:
        - - $namespace=devops-sso-${ENV_NAME}
          - app=sso-${ENV_NAME}
