---
# without this policy, pods could have PU Update error when starting teh container
apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: custom-pods-to-api-zeva
spec:
  description: |
    Allow pods to talk to the internal OCP api
  source:
  - - $namespace=tbiwaq-dev
  destination:
  - - int:network=internal-cluster-api-endpoint
#---
#apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
#kind: NetworkSecurityPolicy
#metadata:
#  name: custom-allow-dev-and-tools-to-talk-zeva
#spec:
#  description: |
#    Allow all pods in dev and tools to communicate
#  source:
#  - - $namespace=tbiwaq-dev
#  - - $namespace=tbiwaq-tools
#  destination:
#  - - $namespace=tbiwaq-tools
#  - - $namespace=tbiwaq-dev
#---
#kind: NetworkSecurityPolicy
#apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
#metadata:
#  name: pods-to-external-network
#  labels:
#    name: pods-to-external-network
#    env: tbiwaq-dev
#spec:
#  description: |
#    Allow the builds to access the internet.
#    This only needs to be specified once for tbiwaq-dev project as build only runs in tools project.
#  source:
#  - - $namespace=tbiwaq-dev
#  destination:
#  - - ext:network=any
