---
kind: Template
apiVersion: v1
labels:
  template: zeva-generic-policy
metadata:
  name: zeva-generic-policy
  creationTimestamp:
parameters:
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment Name
    required: true
  - name: OCP_NAME
    displayName: Openshift Name
    description: Openshift Name
    required: true    
objects:
  - kind: NetworkSecurityPolicy
    apiVersion: secops.${OCP_NAME}.gov.bc.ca/v1alpha1
    metadata:
      name: egress-internet
    spec:
      description: |
        allow the tbiwaq-${ENV_NAME} namespace to talk to the internet.
      source:
        - - $namespace=tbiwaq-${ENV_NAME}
      destination:
        - - ext:network=any
  - kind: NetworkSecurityPolicy
    apiVersion: secops.${OCP_NAME}.gov.bc.ca/v1alpha1
    metadata:
      name: intra-namespace-comms
    spec:
      description: |
        allow the tbiwaq-${ENV_NAME} namespace to talk to itself
      source:
        - - $namespace=tbiwaq-${ENV_NAME}
      destination:
        - - $namespace=tbiwaq-${ENV_NAME}
  - kind: NetworkSecurityPolicy
    apiVersion: secops.${OCP_NAME}.gov.bc.ca/v1alpha1
    metadata:
      name: int-cluster-k8s-api-comms
    spec:
      description: |
        allow tbiwaq-${ENV_NAME} pods to talk to the k8s api
      destination:
        - - int:network=internal-cluster-api-endpoint
      source:
        - - $namespace=tbiwaq-${ENV_NAME}