apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  name: ${NAME}-frontend${SUFFIX}
  labels:
    shared: "true"    
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: ${NAME}-frontend:${VERSION}
  postCommit: {}
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  runPolicy: Serial
  source:
    git:
      ref: ${GIT_REF}
      uri: ${GIT_URL}
    type: Git
    contextDir: frontend
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs-16:1-59
        namespace: e52f12-tools
      pullSecret:
        name: zeva-image-pull-secret
      forcePull: true
      noCache: true          
      env:
        - name: ARTIFACTORY_USER
          valueFrom:
            secretKeyRef:
              name: artifacts-zeva-artifactory-service-account-xgchey
              key: username
        - name: ARTIFACTORY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: artifacts-zeva-artifactory-service-account-xgchey
              key: password
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
status:
  lastVersion: 0