{{- if .Values.frontendRoute.create }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels: {{ include "zeva-frontend.labels" . | nindent 4 }}
  name: {{ template "zeva-frontend.name" . }}-sockjs-node{{ .Values.suffix}}
spec:
  host: {{ .Values.appConfigMap.hostName }}
  path: /sockjs-node
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ template "zeva-frontend.name" . }}{{ .Values.suffix}}
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  annotations:      
    haproxy.router.openshift.io/timeout: 1500s            
  labels: {{ include "zeva-frontend.labels" . | nindent 4 }}
  name: {{ template "zeva-frontend.name" . }}{{ .Values.suffix}}
spec:
  host: {{ .Values.appConfigMap.hostName }}
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ template "zeva-frontend.name" . }}{{ .Values.suffix}}
    weight: 100
  wildcardPolicy: None
{{- end }}