apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: {{ template "zeva-frontend.name" . }}{{ .Values.suffix}}
  labels: {{ include "zeva-frontend.labels" . | nindent 4 }}
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: websocket-notifications
      port: 5002
      protocol: TCP
      targetPort: 5002
  selector: {{ include "zeva-frontend.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}